### ISSUE TITLE
cannot build icu

### ISSUE THREAD

**Issue by koztay** [ovalhub/pyicu#100]
I am having build issue with icu and I am getting the following error : 

` Running setup.py install for PyICU: started
    Running setup.py install for PyICU: finished with status 'error'
    Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-2zok0sfn/PyICU/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-mai9vt2s/install-record.txt --single-version-externally-managed --compile:
    (running 'icu-config --version')
    
    Building PyICU 2.3 for ICU 62.1
    
    (running 'icu-config --cxxflags --cppflags')
    Adding CFLAGS="-std=c++11 -I/usr/include" from /usr/bin/icu-config
    (running 'icu-config --ldflags')
    Adding LFLAGS="-L/usr/lib -licui18n -licuuc -licudata" from /usr/bin/icu-config
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    copying PyICU.py -> build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/icu
    copying icu/__init__.py -> build/lib.linux-x86_64-3.6/icu
    running build_ext
    building '_icu' extension
    creating build/temp.linux-x86_64-3.6
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c _icu.cpp -o build/temp.linux-x86_64-3.6/_icu.o -std=c++11 -I/usr/include -DPYICU_VER="2.3"
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c bases.cpp -o build/temp.linux-x86_64-3.6/bases.o -std=c++11 -I/usr/include -DPYICU_VER="2.3"
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c calendar.cpp -o build/temp.linux-x86_64-3.6/calendar.o -std=c++11 -I/usr/include -DPYICU_VER="2.3"
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c casemap.cpp -o build/temp.linux-x86_64-3.6/casemap.o -std=c++11 -I/usr/include -DPYICU_VER="2.3"
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c char.cpp -o build/temp.linux-x86_64-3.6/char.o -std=c++11 -I/usr/include -DPYICU_VER="2.3"
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c charset.cpp -o build/temp.linux-x86_64-3.6/charset.o -std=c++11 -I/usr/include -DPYICU_VER="2.3"
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c collator.cpp -o build/temp.linux-x86_64-3.6/collator.o -std=c++11 -I/usr/include -DPYICU_VER="2.3"
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c common.cpp -o build/temp.linux-x86_64-3.6/common.o -std=c++11 -I/usr/include -DPYICU_VER="2.3"
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c dateformat.cpp -o build/temp.linux-x86_64-3.6/dateformat.o -std=c++11 -I/usr/include -DPYICU_VER="2.3"
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c errors.cpp -o build/temp.linux-x86_64-3.6/errors.o -std=c++11 -I/usr/include -DPYICU_VER="2.3"
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c format.cpp -o build/temp.linux-x86_64-3.6/format.o -std=c++11 -I/usr/include -DPYICU_VER="2.3"
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c idna.cpp -o build/temp.linux-x86_64-3.6/idna.o -std=c++11 -I/usr/include -DPYICU_VER="2.3"
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c iterators.cpp -o build/temp.linux-x86_64-3.6/iterators.o -std=c++11 -I/usr/include -DPYICU_VER="2.3"
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c layoutengine.cpp -o build/temp.linux-x86_64-3.6/layoutengine.o -std=c++11 -I/usr/include -DPYICU_VER="2.3"
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c locale.cpp -o build/temp.linux-x86_64-3.6/locale.o -std=c++11 -I/usr/include -DPYICU_VER="2.3"
    In file included from locale.cpp:30:
    /usr/include/sys/fcntl.h:1:2: warning: #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h> [-Wcpp]
     #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h>
      ^~~~~~~
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c measureunit.cpp -o build/temp.linux-x86_64-3.6/measureunit.o -std=c++11 -I/usr/include -DPYICU_VER="2.3"
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c normalizer.cpp -o build/temp.linux-x86_64-3.6/normalizer.o -std=c++11 -I/usr/include -DPYICU_VER="2.3"
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c numberformat.cpp -o build/temp.linux-x86_64-3.6/numberformat.o -std=c++11 -I/usr/include -DPYICU_VER="2.3"
    numberformat.cpp: In function 'PyObject* t_unlocalizednumberformatter_grouping(t_unlocalizednumberformatter*, PyObject*)':
    numberformat.cpp:3178:37: error: 'UNumberGroupingStrategy' was not declared in this scope
                 self->object->grouping((UNumberGroupingStrategy) strategy));
                                         ^~~~~~~~~~~~~~~~~~~~~~~
    numberformat.cpp:3178:37: note: suggested alternative: 'UNumberGroupingStrategyType_'
                 self->object->grouping((UNumberGroupingStrategy) strategy));
                                         ^~~~~~~~~~~~~~~~~~~~~~~
                                         UNumberGroupingStrategyType_
    numberformat.cpp: In function 'PyObject* t_localizednumberformatter_grouping(t_localizednumberformatter*, PyObject*)':
    numberformat.cpp:3402:37: error: 'UNumberGroupingStrategy' was not declared in this scope
                 self->object->grouping((UNumberGroupingStrategy) strategy));
                                         ^~~~~~~~~~~~~~~~~~~~~~~
    numberformat.cpp:3402:37: note: suggested alternative: 'UNumberGroupingStrategyType_'
                 self->object->grouping((UNumberGroupingStrategy) strategy));
                                         ^~~~~~~~~~~~~~~~~~~~~~~
                                         UNumberGroupingStrategyType_
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-2zok0sfn/PyICU/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-mai9vt2s/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-2zok0sfn/PyICU/
You are using pip version 19.0.3, however version 19.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

I am using the following Dockerfile for building:

`FROM python:3-alpine
RUN apk --no-cache add icu-libs icu-dev gcc g++ \
    
&& pip3 install --no-cache-dir polyglot futures Morfessor numpy pycld2 PyICU six \
    
&& apk del icu-dev gcc g++`

**Comment by ovalhub** [comment]
Indeed, there is a bug here when building PyICU 2.3 with ICU 62.1.
UNumberGroupingStrategy exists in ICU 61 but is called UGroupingStrategy 
until ICU 63. It was renamed to UNumberGroupingStrategy in ICU 63.
(yet is documented at @since ICU 61).

Please insert the following lines:

#if U_ICU_VERSION_HEX < VERSION_HEX(63, 0, 0)
using UNumberGroupingStrategy = UGroupingStrategy;
#endif

just after line 53 in numberformat.cpp and let me know if it fixes the 
problem. If it does, I'll release 2.3.1 with the fix to PyPI.

Thanks !

Andi..

**Comment by koztay** [comment]
Hi Andi,
You saved my day, thank you very very much. It fixes the problem and you can release 2.3.1 with the fix to PyPI.

**Comment by ovalhub** [comment]
super, thanks for letting me know !
Andi..

**Comment by ovalhub** [comment]
fixed in PyICU 2.3.1
