### ISSUE TITLE
Feature request: Replaceable support for Transliterator

### ISSUE THREAD

**Issue by tavianator** [ovalhub/pyicu#107]
ICU has a [Replaceble](http://icu-project.org/apiref/icu4c/classReplaceable.html) interface that can be passed to [Transliterator](http://icu-project.org/apiref/icu4c/classicu_1_1Transliterator.html) if you want to keep track of where the changes happen.  It would be great if custom Replaceable implementations could be provided rather than just strings.

**Comment by ovalhub** [comment]
On Fri, 2 Aug 2019, Tavian Barnes wrote:

> ICU has a [Replaceble](http://icu-project.org/apiref/icu4c/classReplaceable.html) interface that can be passed to [Transliterator](http://icu-project.org/apiref/icu4c/classicu_1_1Transliterator.html) if you want to keep track of where the changes happen.  It would be great if custom Replaceable implementations could be provided rather than just strings.

How would you provide the custom Replaceable implementation to PyICU ?

**Comment by ovalhub** [comment]
Currently, PyICU is a wrapper around existing C/C++ ICU code.
Extending ICU C++ classes from Python is not supported by PyICU.
That being said, it could be implemented in a reverse-wrapper kind of way, a 
bit like JCC does with Java:
   http://lucene.apache.org/pylucene/jcc/index.html
You could define a C++ extension of Replaceable that wraps a pure Python 
implementation. The methods on the C++ extenstion would call the Python 
methods.

Andi..

**Comment by ovalhub** [comment]
This feature is now implemented in HEAD. Please, check it out and let me know if it works as expected for you. I, so far, only added PythonReplaceable support in the Transliterator methods that accept it. If there are other such methods accepting Replaceable you'd like support added for, please let me know. Thanks !

**Comment by ovalhub** [comment]
I forgot to mention that I also added a test that shows how to create your own python implementation of a Replaceable, wrap it for ICU with PythonReplaceable and use it with a Transliterator instance.

**Comment by tavianator** [comment]
Great, thanks!  I'll try it out.

**Comment by ovalhub** [comment]
On Wed, 2 Oct 2019, Tavian Barnes wrote:

> Great, thanks!  I'll try it out.

Note that I also just found again something I had implemented years ago that 
might be relevant for your use case. There is a PythonTransliterator 
C++ class in transliterator.cpp that lets you define a Transliterator 
subclass in Python using a similar technique by only implementing the 
handleTransliterate() method. There is a test for it, showing you how it can 
be done, in test_Transliterator.py as well.

**Comment by tavianator** [comment]
Just tried this out, it appears to work.  Thanks!

**Comment by ovalhub** [comment]
On Fri, 4 Oct 2019, Tavian Barnes wrote:

> Just tried this out, it appears to work.  Thanks!

Great, thanks for checking. I hence consider the feature done.

**Comment by ovalhub** [comment]
released in PyICU 2.4
