### ISSUE TITLE
Suggestion: Set up Travis CI to test multuple platforms and ICU versions

### ISSUE THREAD

**Issue by SethMMorton** [ovalhub/pyicu#117]
I note that this repository has a `.travis-ci.yml` file, but based on [a comment in another issue](https://github.com/ovalhub/pyicu/issues/114#issuecomment-553257877) this repository is not actually connected to Travis-CI.

As a first step, I would recommend connecting this repository to Travis-CI (if I recall it is very simple). This way, it can be seen if the `.travis-ci.yml` currently in the repo is even valid.

If this is set up, I (or someone else) can submit a PR to help update the `.travis-ci.yml` file to support multiple platforms and multiple ICU versions, so that finding bugs before release is much simpler.

**Comment by ovalhub** [comment]
Done (not sure I got the free option, it's unclear): https://travis-ci.com/ovalhub/pyicu.
Please, submit a PR with your config at your convenience.

**Comment by SethMMorton** [comment]
I'll start taking a look.

Based on some of the errors you have seen recently, do you have a feel for what might be a good list of ICU versions to include in the test suite?

**Comment by ovalhub** [comment]
On Wed, 13 Nov 2019, Seth Morton wrote:

> I'll start taking a look.
>
> Based on some of the errors you have seen recently, do you have a feel for 
> what might be a good list of ICU versions to include in the test suite?

Anything that isn't recent ICU, anything not Mac or Linux.
In particular, I have no access to Windows and its compilers.

I don't test with ICU versions other than current and current but one. Same 
with Python 2 and 3 versions. I only test with Python 2.7.16 and 3.7 and 
3.8 at the moment.

**Comment by SethMMorton** [comment]
> not sure I got the free option, it's unclear

travis-ci.org is the one I use, which I guess is only for public repos. travis-ci.com looks _identical_ but apparently is for private as well.  That is ultra-confusing.

**Comment by ovalhub** [comment]
On Thu, 14 Nov 2019, Seth Morton wrote:

>> not sure I got the free option, it's unclear
>
> travis-ci.org is the one I use, which I guess is only for public repos. 
> travis-ci.com looks _identical_ but apparently is for private as well. 
> That is ultra-confusing.

Ah ha, I'll switch to using the .org version of this.
Thanks !

**Comment by ovalhub** [comment]
Your PR was merged and this suggestion is now implemented (with the exception of windows support, partially there).
