### ISSUE TITLE
Suggestion: Release wheels of PyICU

### ISSUE THREAD

**Issue by SethMMorton** [ovalhub/pyicu#119]
References: #118 and #117.

PyICU is attempting to be compatible with all 15 "active" versions of ICU. Attempting to keep one library compatible with 15 third-party library versions, 5 Python versions, and 3 OSs is asking for a LOT of work (135 permutations!), especially for a single developer. I do not really think that the open source community expects/should expect one developer to support such modularity.

If it were me, I would not attempt to support so many ICU versions. I would do both of the following:

- Compile the latest ICU as a static library, then release wheels for PyICU linked against that ICU version 
  - This has three huge benefits
    1. You only *really* need to test against the ICU version against which you ship
    2. The user does not need to install ICU themselves/ahead of time before installing/using PyICU, which lowers the barrier of entry to using the library (a bigger deal than you might think)
    3. `pip install pyicu` can be done without a compiler
- Specify in your README in the installation instructions section against which ICU versions the given PyICU version is valid with, so that folks that want to build from source (such as distro package maintainers) can be assure some level of compatibility
  - You would add tests only against the listed versions in the CI

Creating/uploading wheels can be done through CI with a package like https://github.com/joerick/cibuildwheel, so it's not necessarily a whole lot of extra work once the CI configuration is done.

**Comment by ovalhub** [comment]
On Fri, 15 Nov 2019, Seth Morton wrote:

> References: #118 and #117.
>
> PyICU is attempting to be compatible with all 15 "active" versions of ICU. 
> Attempting to keep one library compatible with 15 third-party library 
> versions, 5 Python versions, and 3 OSs is asking for a LOT of work (135 
> permutations!), especially for a single developer. I do not really think 
> that the open source community expects/should expect one developer to 
> support such modularity.

I think it's fine to support such modularity. If people with different 
combos were a bit more vocal and would send in patches for build fixes, it 
would all be possible to do sanely. As it is, it's not until I make a 
release that people complain about build errors due to untested combos.

The number of combos is even larger. A sizable amount of build issues I 
receive is from people using something called Anaconda. I have no idea what 
this thing even is... And they usually seem to have no idea what it means to 
build a C++ python extension.

> If it were me, I would not attempt to support so many ICU versions. I 
> would do both of the following:
>
> - Compile the latest ICU as a static library, then release wheels for 
> PyICU linked against that ICU version

I am *not* ever releasing binaries. This is a responsibilty I refuse to 
take. Others have in the past, with another open source project of mine,
JCC (https://pypi.org/project/JCC/) started a "binary fork" (especially for 
Windows binaries), and released binaries for their favorite combos (just 
the number of Windows combos can be mind boggling).

I encourage volunteers to release wheels with binaries if they like. I am 
not doing that, though. This is the power of open source !

>  - This has three huge benefits
>    1. You only *really* need to test against the ICU version against which you ship
>    2. The user does not need to install ICU themselves/ahead of time before installing/using PyICU, which lowers the barrier of entry to using the library (a bigger deal than you might think)
>    3. `pip install pyicu` can be done without a compiler

Agreed. It would be nice. But I'm not taking the responsiblity of shipping 
binaries.

> - Specify in your README in the installation instructions section against which ICU versions the given PyICU version is valid with, so that folks that want to build from source (such as distro package maintainers) can be assure some level of compatibility
>  - You would add tests only against the listed versions in the CI
>
> Creating/uploading wheels can be done through CI with a package like https://github.com/joerick/cibuildwheel, so it's not necessarily a whole lot of extra work once the CI configuration is done.

If this can be automated then i encourage some volunteers to set this up 
and maintain it !

**Comment by SethMMorton** [comment]
It's not clear to me if you are opposed to binaries coming from this repository or if they must come from elsewhere.  For example, if someone were to set it up so that binaries were automatically created and released when you tagged a commit, would that be OK? Or are you saying that if binaries are released it's OK as long it does not come from this repository?

Also, can I ask why not binaries? From a user perspective, it's much nicer when a module does not need to be compiled at build time since that compilation time really slows down unit test startup and CI builds. For my C extension project I started releasing binaries when I got issues about compilation, and it has been a very easy and no-maintenance situation for me.

**Comment by ovalhub** [comment]
On Fri, 15 Nov 2019, Seth Morton wrote:

> It's not clear to me if you are opposed to binaries coming from this 
> repository or if they must come from elsewhere.  For example, if someone 
> were to set it up so that binaries were automatically created and released 
> when you tagged a commit, would that be OK? Or are you saying that if 
> binaries are released it's OK as long it does not come from this 
> repository?

I'm opposed to having my name attached to binaries. It's a responsibility 
I'm not willing to take. If "this repository" means that my name is attached 
to the binaries, then I'm opposed to it.

> Also, can I ask why not binaries? From a user perspective, it's much nicer 
> when a module does not need to be compiled at build time since that 
> compilation time really slows down unit test startup and CI builds. For my 
> C extension project I started releasing binaries when I got issues about 
> compilation, and it has been a very easy and no-maintenance situation for 
> me.

I cannot vouch that the binaries are virus free. If someone takes these 
binaries and copies them to another system, with a different config, it's 
another can of worms explaining to people their dynamic linker errors.
