### ISSUE TITLE
Non-existent homepage in README

### ISSUE THREAD

**Issue by jwilk** [ovalhub/pyicu#12]
README reads:

> The PyICU homepage is http://pyicu.osafoundation.org.

But this domain doesn't seem to exist.

**Comment by ovalhub** [comment]
Yes, osafoundation.org finally disappeared completely a couple of months ago.

**Comment by ezmiller** [comment]
@ovalhub what does this mean in the bigger picture vis-a-vis this project, if anything?

**Comment by ovalhub** [comment]
> On Feb 6, 2016, at 08:04, Ethan Miller <notifications@github.com> wrote:
> 
> @ovalhub what does this mean in the bigger picture vis-a-vis this project, if anything?
> 
What does "what" mean ?

**Comment by ovalhub** [comment]
> On Feb 6, 2016, at 08:04, Ethan Miller <notifications@github.com> wrote:
> 
> @ovalhub what does this mean in the bigger picture vis-a-vis this project, if anything?
> 

Ah, sorry, it's in the subject line. OSAF, where I started this project in 2004, and which was hosting it, finally dropped off the internet. I moved it to github instead.

**Comment by jwilk** [comment]
I see that README was updated in b002648c909342cd7670b8824bced9cedae22346, but there are still a references to `osafoundation.org` in `setup.py`.

**Comment by ovalhub** [comment]
On Tue, 19 Jul 2016, Jakub Wilk wrote:

> I see that README was updated in b002648c909342cd7670b8824bced9cedae22346, but there are still a references to `osafoundation.org` in `setup.py`.

Fixed !

Andi..
