### ISSUE TITLE
testLocaleMatcher not skipped on old ICU when run via pytest

### ISSUE THREAD

**Issue by mkszuba** [ovalhub/pyicu#120]
Although testLocaleMatcher does check if the underlying ICU version is at least 65.0 before proceeding, it only only seems to do so when the script in question is run directly. As a result, when I attempted to run the test suite from the upcoming Gentoo ebuild for 2.4.2 on a system with ICU-64.2, which ebuilds call pytest on the unit-test directory rather than invoke individual scripts, I saw errors.
The attached patch solves the problem for me. It may or may not make the original version check unnecessary, I haven't tried.
[pyicu-2.4.2-testLocaleMatcher_pytest_old_icu.txt](https://github.com/ovalhub/pyicu/files/3983705/pyicu-2.4.2-testLocaleMatcher_pytest_old_icu.txt)

**Comment by ovalhub** [comment]
I believe I fixed all these issues in HEAD when we setup travis CI a few weeks ago (but I haven't looked at your patch yet)

**Comment by mkszuba** [comment]
Indeed fixed on master (d'oh, should have looked there too), except you have done it by implementing the skip in unittest-compatible fashion by placing in the set-up method whereas my patch uses a pytest annotator (skipif). Seeing as pytest is explicitly mentioned in listed as a test dependency in setup.py, one might wonder stick with the former approach - but in the end, whatever works!
