### ISSUE TITLE
Missing binding for `getPropertyValueName` and `getPropertyValueNameEnum`

### ISSUE THREAD

**Issue by glebm** [ovalhub/pyicu#122]
These methods are missings and without them it doesn't seem to be possible to obtain human-readable names for Unicode property values.

**Comment by ovalhub** [comment]
Indeed, they are missing. Maybe it's because I didn't understand what they did.
I added those just now in HEAD.
Please, try them out and let me if they work as you'd expect.
Thanks !

**Comment by glebm** [comment]
That was quick! Thanks!
