### ISSUE TITLE
Installation on macOS 10.15.1 with Homebrew icu4c

### ISSUE THREAD

**Issue by chrissimpkins** [ovalhub/pyicu#123]
macOS 10.15.1
Python 3.7.6 (Homebrew version)
pkg-config 0.29.2 (Homebrew version)

This information is unfortunately not easy to come by so I am posting it here for others who might find it useful.  The sources are [here](https://tobywf.com/2017/05/installing-pyicu-on-macos/) and [here](https://stackoverflow.com/a/50208262).  It is possible that all steps may not be necessary, but they did lead to a successful build for me after receiving the following `pip3 install pyicu` error:

```
RuntimeError:
    Please install pkg-config on your system or set the PYICU_CFLAGS environment
    variable to the flags required by the C++ compiler to find the header files
    for ICU, and possibly -std=c++11 if using ICU version >= 60
```

## Install icu4c with Homebrew

```
brew install icu4c
```

## Set env vars

**_Edit_**: See https://github.com/ovalhub/pyicu/issues/123#issuecomment-574906038 for a simpler approach to this step.

Use the version number from the `ls` step for the version strings in `ICU_VERSION`, `PYICU_INCLUDES`, and `PYICU_LFLAGS`.  Use the [pyicu library version](https://github.com/ovalhub/pyicu/blob/19e4397ae0e5ca1f02fa0930915bcffb1efaa49b/setup.py#L11) for the `PYICU_CFLAGS` `-DPYICU_VER` field.

```
$ ls /usr/local/Cellar/icu4c
$ export ICU_VERSION=64
$ export PYICU_INCLUDES=/usr/local/Cellar/icu4c/64.2/include
$ export PYICU_LFLAGS=-L/usr/local/Cellar/icu4c/64.2/lib
$ export PYICU_CFLAGS=-std=c++11:-DPYICU_VER='"2.4.2"'
```

## Install

```
$ pip3 install pyicu
```

**Comment by dlukes** [comment]
Thanks, that was really helpful!

**Comment by dlukes** [comment]
A quick update: adding the `icu-config` program to your `PATH` instead of setting all of those flags manually should also work (as in, it did in my case :) ):

```sh
export PATH="/usr/local/opt/icu4c/bin:$PATH"
pip3 install pyicu
```

**Comment by chrissimpkins** [comment]
That is a much better approach!  So the steps are?:

```
$ brew install icu4c
$ export PATH="/usr/local/opt/icu4c/bin:$PATH"
$ pip3 install pyicu
```

**Comment by dlukes** [comment]
To be fair, the README does mention that `icu-config` should be enough, I just thought it already *was* on my `PATH`, as with other stuff installed by Homebrew. So when compilation failed, I skipped to trying out to figure out the more complicated way with setting all the other env vars manually, which your OP told me how to get right :)

**Comment by chrissimpkins** [comment]
> I just thought it already was on my PATH, as with other stuff installed by Homebrew.

👍

**Comment by te0006** [comment]
Had the same problem on Ubuntu 16.04.6 LTS. 
I needed pyicu as a dependency for polyglot.
At first I tried to build icu4c locally, set the environment variables as shown above, and then to install pyicu using pip. This almost worked but there was a dynamic linker error on import of the resulting pyico extension.
What finally did it was the solution from https://github.com/aboSamoor/polyglot/issues/89: 

>conda install icu
>conda install -c conda-forge pyicu
>pip install pycld2

After this, pyicu finally worked and
>pip install polyglot
was successful as well.
