### ISSUE TITLE
Import error with ICU 67

### ISSUE THREAD

**Issue by blackblitz** [ovalhub/pyicu#127]
PyICU suddenly started compaining
```
ImportError: libicui18n.so.65: cannot open shared object file: No such file or directory
```
when I tried to import it in python. This can be solved by downgrading to ICU 65, but this breaks other software which depends on ICU 67, specifically gnumeric.

**Comment by ovalhub** [comment]
> On May 10, 2020, at 21:59, William (Wai Yan) Zhu <notifications@github.com> wrote:
> 
> PyICU suddenly started compaining
> 
> ImportError: libicui18n.so.65: cannot open shared object file: No such file or directory
> when I tried to import it in python. This can be solved by downgrading to ICU 65, but this breaks other software which depends on ICU 67, specifically gnumeric.
> 
If you upgraded icu you should rebuild pyicu.

Andi..

**Comment by blackblitz** [comment]
> On May 10, 2020, at 21:59, William (Wai Yan) Zhu ***@***.***> wrote: PyICU suddenly started compaining ImportError: libicui18n.so.65: cannot open shared object file: No such file or directory when I tried to import it in python. This can be solved by downgrading to ICU 65, but this breaks other software which depends on ICU 67, specifically gnumeric.
> If you upgraded icu you should rebuild pyicu. Andi..
> […](#)
> — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks. Previously, pip was using the cached version whenever I tried to reinstall. With `--no-cache-dir`, I was able to rebuild and reinstall.
