### ISSUE TITLE
How to use DictionaryBasedBreakIterator from PyICU?

### ISSUE THREAD

**Issue by wannaphong** [ovalhub/pyicu#128]
How to use DictionaryBasedBreakIterator from PyICU? Could you suggest?

**Comment by ovalhub** [comment]
On Thu, 28 May 2020, Wannaphong Phatthiyaphaibun wrote:

> How to use DictionaryBasedBreakIterator from PyICU? Could you suggest?

That class has been deprecated since ICU 3.6:
   https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/namespaceicu.html#ae44e1ab9362b6cb8800a082395f50294
It looks like you should use RuleBasedBreakIterator instead.

Andi..

**Comment by wannaphong** [comment]
@ovalhub Sad. :(  
Can RuleBasedBreaklterator custom a dictionary for word break?

**Comment by ovalhub** [comment]
> On May 28, 2020, at 23:05, Wannaphong Phatthiyaphaibun <notifications@github.com> wrote:
> 
> ﻿
> @ovalhub Sad. :(
> 
The class is still available in pyicu, though. You're welcome to use it - it's just not well documented by icu.
> Can RuleBasedBreaklterator custom a dictionary for word break?
> 
I don't know but the docs seem to imply so. For questions about how to use icu, please ask on the icu users mailing list. There is a lot more expertise about icu apis there.

Andi..

**Comment by wannaphong** [comment]
> 
> On May 28, 2020, at 23:05, Wannaphong Phatthiyaphaibun ***@***.***> wrote: ﻿ @ovalhub Sad. :(
> The class is still available in pyicu, though. You're welcome to use it - it's just not well documented by icu.
> Can RuleBasedBreaklterator custom a dictionary for word break?
> I don't know but the docs seem to imply so. For questions about how to use icu, please ask on the icu users mailing list. There is a lot more expertise about icu apis there. Andi..
> […](#)
> — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you.
