### ISSUE TITLE
Sharing your SWIG interface

### ISSUE THREAD

**Issue by tylerpayne** [ovalhub/pyicu#129]
Thanks for this very useful binding.

I imagine you used SWIG to generate the bindings. Would you mind sharing your interface file and/or any issues you ran into SWIGing icu4c?

**Comment by ovalhub** [comment]
On Mon, 8 Jun 2020, Tyler Payne wrote:

> Thanks for this very useful binding.
>
> I imagine you used SWIG to generate the bindings. Would you mind sharing 
> your interface file and/or any issues you ran into SWIGing icu4c?

I did *not* use SWIG for this since 2006.
The PyICU bindings have been written by hand since then.

**Comment by tylerpayne** [comment]
My mistake! Thanks for the quick response.
