### ISSUE TITLE
Use of deprecated APIs.

### ISSUE THREAD

**Issue by methane** [ovalhub/pyicu#131]
These APIs are deprecated since Python 3.3 and we are planning to remove them in 3.11.
See also https://docs.python.org/3/c-api/unicode.html#deprecated-py-unicode-apis

```
./PyICU-2.5/bases.cpp:2013:        return PyUnicode_FromUnicode(&c, 1);
./PyICU-2.5/charset.cpp:336:    return PyUnicode_FromUnicode(NULL, 0);
./PyICU-2.5/common.cpp:177:        return PyUnicode_FromUnicode((const Py_UNICODE *) utf16, len16);
./PyICU-2.5/common.cpp:181:        PyObject *u = PyUnicode_FromUnicode(NULL, len32);
./PyICU-2.5/common.cpp:359:                  Py_UNICODE *pchars = PyUnicode_AsUnicodeAndSize(object, &len);
./PyICU-2.5/common.cpp:366:                  Py_UNICODE *pchars = PyUnicode_AsUnicodeAndSize(object, &len);
```

**Comment by ovalhub** [comment]
On Sat, 13 Jun 2020, Inada Naoki wrote:

> These APIs are deprecated since Python 3.3 and we are planning to remove them in 3.11.
> See also https://docs.python.org/3/c-api/unicode.html#deprecated-py-unicode-apis

Thank you for the heads up !

> ./PyICU-2.5/bases.cpp:2013:        return PyUnicode_FromUnicode(&c, 1);
Done.

> ./PyICU-2.5/charset.cpp:336:    return PyUnicode_FromUnicode(NULL, 0);
Done.

> ./PyICU-2.5/common.cpp:177:        return PyUnicode_FromUnicode((const Py_UNICODE *) utf16, len16);
> ./PyICU-2.5/common.cpp:181:        PyObject *u = PyUnicode_FromUnicode(NULL, len32);
These two are for pre 3.3 python code.

> ./PyICU-2.5/common.cpp:359:                  Py_UNICODE *pchars = PyUnicode_AsUnicodeAndSize(object, &len);
> ./PyICU-2.5/common.cpp:366:                  Py_UNICODE *pchars = PyUnicode_AsUnicodeAndSize(object, &len);
Done (although I'm confused if this code path can actually happen).
In other words, in what situation is PyUnicode_WCHAR_KIND returned by 
PyUnicode_Kind(object) ?

**Comment by methane** [comment]
Thank you for quick fix!

> In other words, in what situation is PyUnicode_WCHAR_KIND returned by
> PyUnicode_Kind(object) ?

I think it is never returned after Python 3.11.
