### ISSUE TITLE
Building PyICU 2.5 for ICU 67 fails on Windows

### ISSUE THREAD

**Issue by cgohlke** [ovalhub/pyicu#135]
I am unable to build PyICU-2.5 or the git master branch against ICU 67.1 on Windows using Visual Studio 2017 or 2015, any Python version. Building PyICU-2.4.3 against the same ICU, compiler, and Python versions works.

The error is:

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:/icu/include -IX:\Python38\include -IX:\Python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -IX:\Cmd -IX:\Python38\include -IX:\inclib-vc15-x64 "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tp_icu.cpp /Fobuild\temp.win-amd64-3.8\Release\_icu.obj /Zc:wchar_t /EHsc /DU_STATIC_IMPLEMENTATION /DPYICU_VER=\"2.5\" /DPYICU_ICU_MAX_VER=\"67\"
_icu.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xxatomic(390): error C2036: '_Ty *': unknown size
        with
        [
            _Ty=icu_67::number::impl::NumberRangeFormatterImpl
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xxatomic(389): note: while compiling class template member function '_Ty *std::atomic<icu_67::number::impl::NumberRangeFormatterImpl *>::operator -=(ptrdiff_t) noexcept'
        with
        [
            _Ty=icu_67::number::impl::NumberRangeFormatterImpl
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xxatomic(410): note: see reference to function template instantiation '_Ty *std::atomic<icu_67::number::impl::NumberRangeFormatterImpl *>::operator -=(ptrdiff_t) noexcept' being compiled
        with
        [
            _Ty=icu_67::number::impl::NumberRangeFormatterImpl
        ]
X:\inclib-vc15-x64\unicode/numberrangeformatter.h(197): note: see reference to class template instantiation 'std::atomic<icu_67::number::impl::NumberRangeFormatterImpl *>' being compiled
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
```

**Comment by ovalhub** [comment]
I have no access to Windows and its compilers so I can't reproduce and debug this. I'm sorry to not be able to help you much.
Andi..

**Comment by cgohlke** [comment]
Thank you. There is Windows specific code for `NumberRangeFormatterImpl` adding explicit template instantiation in ICU's [numberrangeformatter.h](https://github.com/unicode-org/icu/blob/125e29d54990e74845e1546851b5afa3efab06ce/icu4c/source/i18n/unicode/numberrangeformatter.h#L188-L202). Could that be the culprit?

```C++
/**
 * \cond
 * Export an explicit template instantiation. See datefmt.h
 * (When building DLLs for Windows this is required.)
 */
#if U_PLATFORM == U_PF_WINDOWS && !defined(U_IN_DOXYGEN)
} // namespace icu::number
U_NAMESPACE_END


template struct U_I18N_API std::atomic< U_NAMESPACE_QUALIFIER number::impl::NumberRangeFormatterImpl*>;


U_NAMESPACE_BEGIN
namespace number {  // icu::number
#endif
/** \endcond */
```

**Comment by cgohlke** [comment]
PyICU builds without error after removing the explicit template instantiation in ICU.

**Comment by cgohlke** [comment]
Unfortunately, `testFromDecimalFormat` crashes when removing the explicit template instantiation in ICU:

```
platform win32 -- Python 3.7.8, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- X:\Python37\python.exe
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('D:\\Build\\libICU\\PyICU-2.5\\test\\.hypothesis\\examples')
rootdir: D:\Build\libICU\PyICU-2.5
plugins: hypothesis-5.20.2, napari-plugin-engine-0.1.6, palladium-1.2.3, cov-2.10.0, forked-1.2.0, localserver-0.5.0, pep8-1.0.6, xdist-1.33.0
collected 59 items

test_BreakIterator.py::TestBreakIterator::testCreateInstanceFromBinaryRules PASSED                               [  1%]
test_BreakIterator.py::TestBreakIterator::testCreateInstancePolymorph PASSED                                     [  3%]
test_BytesTrie.py::TestBytesTrie::testAccess PASSED                                                              [  5%]
test_BytesTrie.py::TestBytesTrie::testBuildAndIterate PASSED                                                     [  6%]
test_Charset.py::TestCharset::testDeclared PASSED                                                                [  8%]
test_Charset.py::TestCharset::testDetect PASSED                                                                  [ 10%]
test_Charset.py::TestCharset::testDetectAll PASSED                                                               [ 11%]
test_Charset.py::TestCharset::testUnicode PASSED                                                                 [ 13%]
test_Collator.py::TestCollator::testAlphabeticIndex PASSED                                                       [ 15%]
test_Collator.py::TestCollator::testCollatorLoading PASSED                                                       [ 16%]
test_Collator.py::TestCollator::testCreateInstancePolymorph PASSED                                               [ 18%]
test_Collator.py::TestCollator::testGetSortKey PASSED                                                            [ 20%]
test_Collator.py::TestCollator::testSort PASSED                                                                  [ 22%]
test_DateTimeParserGenerator.py::TestDateTimePatternGenerator::testAddPattern PASSED                             [ 23%]
test_DateTimeParserGenerator.py::TestDateTimePatternGenerator::testGetBestPattern PASSED                         [ 25%]
test_DateTimeParserGenerator.py::TestDateTimePatternGenerator::testReplaceFieldType PASSED                       [ 27%]
test_ListFormatter.py::TestListFormatter::testDefault PASSED                                                     [ 28%]
test_ListFormatter.py::TestListFormatter::testLocale PASSED                                                      [ 30%]
test_Locale.py::TestLocale::testConstructWithKeywords PASSED                                                     [ 32%]
test_LocaleData.py::TestLocaleData::testCoverage PASSED                                                          [ 33%]
test_LocaleData.py::TestLocaleData::testExemplarSet PASSED                                                       [ 35%]
test_LocaleData.py::TestLocaleData::testExemplarSet2 PASSED                                                      [ 37%]
test_LocaleData.py::TestLocaleData::testLocaleDisplayPattern PASSED                                              [ 38%]
test_LocaleData.py::TestLocaleData::testMeasurementSystem PASSED                                                 [ 40%]
test_LocaleData.py::TestLocaleData::testPapersize PASSED                                                         [ 42%]
test_LocaleMatcher.py::TestLocaleMatcher::testGetBestMatch PASSED                                                [ 44%]
test_LocaleMatcher.py::TestLocaleMatcher::testGetBestMatchResult PASSED                                          [ 45%]
test_LocaleMatcher.py::TestLocaleMatcher::testSetSupportedLocales PASSED                                         [ 47%]
test_MessageFormat.py::TestMessageFormat::testFormat PASSED                                                      [ 49%]
test_MessageFormat.py::TestMessageFormat::testFormatAppend PASSED                                                [ 50%]
test_MessageFormat.py::TestMessageFormat::testFormatMessage PASSED                                               [ 52%]
test_MessageFormat.py::TestMessageFormat::testFormats PASSED                                                     [ 54%]
test_MessageFormat.py::TestMessageFormat::testNamedArgs PASSED                                                   [ 55%]
test_MessageFormat.py::TestMessageFormat::testSelectFormat PASSED                                                [ 57%]
test_Normalizer.py::TestNormalizer2::testNormalize PASSED                                                        [ 59%]
test_NumberFormatter.py::TestNumberFormatter::testBasic PASSED                                                   [ 61%]
test_NumberFormatter.py::TestNumberFormatter::testFancy PASSED                                                   [ 62%]
test_NumberFormatter.py::TestNumberFormatter::testFormattedNumber PASSED                                         [ 64%]
test_NumberFormatter.py::TestNumberFormatter::testFromDecimalFormat Fatal Python error: Aborted

Current thread 0x00001900 (most recent call first):
  File "D:\Build\libICU\PyICU-2.5\test\test_NumberFormatter.py", line 106 in testFromDecimalFormat
```

**Comment by ovalhub** [comment]
On Thu, 30 Jul 2020, Christoph Gohlke wrote:

> PyICU builds without error after removing the explicit template 
> instantiation in ICU.

Interesting. So the problem was with ICU itself ? If so, could you please 
let them know on their support mailing list ?
   http://site.icu-project.org/contacts
Thanks !

**Comment by ovalhub** [comment]
On Thu, 30 Jul 2020, Christoph Gohlke wrote:

> Unfortunately, `testFromDecimalFormat` crashes when removing the explicit template instantiation in ICU:
>
> ```
> platform win32 -- Python 3.7.8, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- X:\Python37\python.exe
> cachedir: .pytest_cache
> hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('D:\\Build\\libICU\\PyICU-2.5\\test\\.hypothesis\\examples')
> rootdir: D:\Build\libICU\PyICU-2.5
> plugins: hypothesis-5.20.2, napari-plugin-engine-0.1.6, palladium-1.2.3, cov-2.10.0, forked-1.2.0, localserver-0.5.0, pep8-1.0.6, xdist-1.33.0
> collected 59 items
>
> test_BreakIterator.py::TestBreakIterator::testCreateInstanceFromBinaryRules PASSED                               [  1%]
> test_BreakIterator.py::TestBreakIterator::testCreateInstancePolymorph PASSED                                     [  3%]
> test_BytesTrie.py::TestBytesTrie::testAccess PASSED                                                              [  5%]
> test_BytesTrie.py::TestBytesTrie::testBuildAndIterate PASSED                                                     [  6%]
> test_Charset.py::TestCharset::testDeclared PASSED                                                                [  8%]
> test_Charset.py::TestCharset::testDetect PASSED                                                                  [ 10%]
> test_Charset.py::TestCharset::testDetectAll PASSED                                                               [ 11%]
> test_Charset.py::TestCharset::testUnicode PASSED                                                                 [ 13%]
> test_Collator.py::TestCollator::testAlphabeticIndex PASSED                                                       [ 15%]
> test_Collator.py::TestCollator::testCollatorLoading PASSED                                                       [ 16%]
> test_Collator.py::TestCollator::testCreateInstancePolymorph PASSED                                               [ 18%]
> test_Collator.py::TestCollator::testGetSortKey PASSED                                                            [ 20%]
> test_Collator.py::TestCollator::testSort PASSED                                                                  [ 22%]
> test_DateTimeParserGenerator.py::TestDateTimePatternGenerator::testAddPattern PASSED                             [ 23%]
> test_DateTimeParserGenerator.py::TestDateTimePatternGenerator::testGetBestPattern PASSED                         [ 25%]
> test_DateTimeParserGenerator.py::TestDateTimePatternGenerator::testReplaceFieldType PASSED                       [ 27%]
> test_ListFormatter.py::TestListFormatter::testDefault PASSED                                                     [ 28%]
> test_ListFormatter.py::TestListFormatter::testLocale PASSED                                                      [ 30%]
> test_Locale.py::TestLocale::testConstructWithKeywords PASSED                                                     [ 32%]
> test_LocaleData.py::TestLocaleData::testCoverage PASSED                                                          [ 33%]
> test_LocaleData.py::TestLocaleData::testExemplarSet PASSED                                                       [ 35%]
> test_LocaleData.py::TestLocaleData::testExemplarSet2 PASSED                                                      [ 37%]
> test_LocaleData.py::TestLocaleData::testLocaleDisplayPattern PASSED                                              [ 38%]
> test_LocaleData.py::TestLocaleData::testMeasurementSystem PASSED                                                 [ 40%]
> test_LocaleData.py::TestLocaleData::testPapersize PASSED                                                         [ 42%]
> test_LocaleMatcher.py::TestLocaleMatcher::testGetBestMatch PASSED                                                [ 44%]
> test_LocaleMatcher.py::TestLocaleMatcher::testGetBestMatchResult PASSED                                          [ 45%]
> test_LocaleMatcher.py::TestLocaleMatcher::testSetSupportedLocales PASSED                                         [ 47%]
> test_MessageFormat.py::TestMessageFormat::testFormat PASSED                                                      [ 49%]
> test_MessageFormat.py::TestMessageFormat::testFormatAppend PASSED                                                [ 50%]
> test_MessageFormat.py::TestMessageFormat::testFormatMessage PASSED                                               [ 52%]
> test_MessageFormat.py::TestMessageFormat::testFormats PASSED                                                     [ 54%]
> test_MessageFormat.py::TestMessageFormat::testNamedArgs PASSED                                                   [ 55%]
> test_MessageFormat.py::TestMessageFormat::testSelectFormat PASSED                                                [ 57%]
> test_Normalizer.py::TestNormalizer2::testNormalize PASSED                                                        [ 59%]
> test_NumberFormatter.py::TestNumberFormatter::testBasic PASSED                                                   [ 61%]
> test_NumberFormatter.py::TestNumberFormatter::testFancy PASSED                                                   [ 62%]
> test_NumberFormatter.py::TestNumberFormatter::testFormattedNumber PASSED                                         [ 64%]
> test_NumberFormatter.py::TestNumberFormatter::testFromDecimalFormat Fatal Python error: Aborted
>
> Current thread 0x00001900 (most recent call first):
>  File "D:\Build\libICU\PyICU-2.5\test\test_NumberFormatter.py", line 106 in testFromDecimalFormat
> ```

That is actually a known bug in ICU (the crash, not the template 
instantiation. They have a fix for it in 67.2 or 68.1. If you need a fix 
sooner (ie, you're actually using that method), please nag them (you can 
quote me on that).

Andi..

**Comment by cgohlke** [comment]
> That is actually a known bug in ICU

Good to know. Otherwise all tests pass.

**Comment by cgohlke** [comment]
> So the problem was with ICU itself ?

I think the preprocessor directive `#if U_PLATFORM == U_PF_WINDOWS && !defined(U_IN_DOXYGEN)` probably needs to be updated for static builds. I'll let ICU know.

**Comment by cgohlke** [comment]
FWIW, while trying to fix these issues, I ran across this suspicious line:

https://github.com/ovalhub/pyicu/blob/965579a33d8d9f1b22a7c0bedab8ec0e51a31bd2/bases.cpp#L658

Shouldn't this be converted to a `Py_ssize_t` instead of `long` since `getDynamicClassID` returns a pointer?

**Comment by ovalhub** [comment]
On Thu, 30 Jul 2020, Christoph Gohlke wrote:

> FWIW, while trying to fix these issues, I ran across this suspicious line:
>
> https://github.com/ovalhub/pyicu/blob/965579a33d8d9f1b22a7c0bedab8ec0e51a31bd2/bases.cpp#L658
>
> Shouldn't this be converted to a `Py_ssize_t` instead of `long` since 
> `getDynamicClassID` returns a pointer?

I don't know about Py_ssize_t but it's declared to return UClassID which is 
declared to be void * thus I'd like to return it as a number.
The code does look suspicious, it should convert via intptr_t or somesuch 
and make a python long long instead of a long.
Then, this is method is pretty useless from Python so the wrapper should be 
removed instead.

**Comment by ovalhub** [comment]
On Thu, 30 Jul 2020, Andi Vajda wrote:

>
> On Thu, 30 Jul 2020, Christoph Gohlke wrote:
>
>> FWIW, while trying to fix these issues, I ran across this suspicious line:
>> 
>> https://github.com/ovalhub/pyicu/blob/965579a33d8d9f1b22a7c0bedab8ec0e51a31bd2/bases.cpp#L658
>> 
>> Shouldn't this be converted to a `Py_ssize_t` instead of `long` since 
>> `getDynamicClassID` returns a pointer?
>
> I don't know about Py_ssize_t but it's declared to return UClassID which is 
> declared to be void * thus I'd like to return it as a number.
> The code does look suspicious, it should convert via intptr_t or somesuch and 
> make a python long long instead of a long.
> Then, this is method is pretty useless from Python so the wrapper should be 
> removed instead.

I ended up fixing the wrapper to match the code in the _str method above it.

static PyObject *t_uobject_getDynamicClassID(t_uobject *self)
{
#if U_ICU_VERSION_HEX < 0x04060000
     return PyInt_FromLong((long) self->object->getDynamicClassID());
#else
     return PyLong_FromUnsignedLongLong(
         (unsigned long long) (intptr_t) self->object->getDynamicClassID());
#endif
}

Thank you for raising this issue !

**Comment by srl295** [comment]
> > So the problem was with ICU itself ?
> 
> I think the preprocessor directive `#if U_PLATFORM == U_PF_WINDOWS && !defined(U_IN_DOXYGEN)` probably needs to be updated for static builds. I'll let ICU know.

the PR (thanks!) is still waiting on a commit message fix…
