### ISSUE TITLE
How install pyicu to ubuntu 20.04? 

### ISSUE THREAD

**Issue by MironenkoSergey** [ovalhub/pyicu#139]
I try install pyicu but have error 
`RuntimeError:
    Please install pkg-config on your system or set the PYICU_CFLAGS environment
    variable to the flags required by the C++ compiler to find the header files
    for ICU, and possibly -std=c++11 if using ICU version >= 60
`
Ubuntu 20.04 have not package python-pyicu

**Comment by ovalhub** [comment]
> On Jan 20, 2021, at 04:43, Mironenko Sergey <notifications@github.com> wrote:
> 
> ﻿
> I try install pyicu but have error
> RuntimeError: Please install pkg-config on your system or set the PYICU_CFLAGS environment variable to the flags required by the C++ compiler to find the header files for ICU, and possibly -std=c++11 if using ICU version >= 60 
> Ubuntu 20.04 have not package python-pyicu
> 
There are packages for pyicu on ubuntu:
https://packages.ubuntu.com/source/xenial/python/pyicu
If you prefer to install it directly, then you need to follow instructions. The error message you included here is asking you to install pkg-config before proceeding. Please, do so using a package listed here:
https://packages.ubuntu.com/search?keywords=pkg-config&searchon=sourcenames

Andi..
