### ISSUE TITLE
Documentation is weak

### ISSUE THREAD

**Issue by ezmiller** [ovalhub/pyicu#14]
I've been trying to develop a flask-icu version of flask-babel with pyicu, and it's been quite slow going because the API documentation is weak. The readme refers us to the documentation for ICU in general, but in many cases that API has been selectively implemented here, and the method argument profiles differ. A particularly confusing area is the documentation of how one might load message data into pyicu. So,  in general, at least some sort of guidance about how to interpret the icu API for pyicu might be of great help.

**Comment by ovalhub** [comment]
> On Feb 6, 2016, at 08:04, Ethan Miller <notifications@github.com> wrote:
> 
> I've been trying to develop a flask-icu version of flask-babel with pyicu, and it's been quite slow going because the API documentation is weak.
> 
It's not weak, it's basically non-existent. The idea is that you use the actual ICU documentation (which is quite complete) together with the PyICU source code.
Each wrapper function follows a more or less similar pattern in mapping inputs and outputs between Python and C++.
> The readme refers us to the documentation for ICU in general, but in many cases that API has been selectively implemented here, and the method argument profiles differ.
> 
They often differ because Python and C++ do things differently. The PyICU interface tries to be more pythonic than sticking to the C++ interface 1 for 1.

Not all functions are implemented, ICU is very large and is adding new ones every release. I attempted to wrap the most useful ones and extra user requests. If you see some missing that you need, please ask about them or, better yet, send in a patch with the new wrappers.
> A particularly confusing area is the documentation of how one might load message data into pyicu.
> 
What do you mean by message data ? which ICU api are you thinking of ?
> So, in general, at least some sort of guidance about how to interpret the icu API for pyicu might be of great help.
> 
Use the source !

Andi..

**Comment by ezmiller** [comment]
@ovalhub thanks for the candid response. I suppose this makes sense if you are in fact not intending to provide any documentation. Might be nice for your users, who are quite possibly less familiar with ICU, to provide some guidance so they can get going quickly. Perhaps even a couple examples. One thing you could do right away is just direct users to your tests. I found them the most clarifying by far.

**Comment by ovalhub** [comment]
> On Feb 9, 2016, at 09:54, Ethan Miller <notifications@github.com> wrote:
> 
> @ovalhub thanks for the candid response. I suppose this makes sense if you are in fact not intending to provide any documentation. Might be nice for your users, who are quite possibly less familiar with ICU, to provide some guidance so they can get going quickly. Perhaps even a couple examples.
> 
That was the intention of the README.md file. It has a few examples like this.
> One thing you could do right away is just direct users to your tests. I found them the most clarifying by far.
> 
I'm glad they were useful. There clearly could be more of them. I believe, I ported a sample or two from C++ icu as well.

In any case, these are all good suggestions, patches are welcome !

Andi..

**Comment by tylercrompton** [comment]
It would help if the wrappers at least had docstrings. Since some things are missing and others have been changed, it'd be helpful to have some docstrings. Even using the ICU documentation, I can't figure out what I'm doing. I am by no means new to programming or using Unicode.

**Comment by tylercrompton** [comment]
Having a few simple, non-exhaustive sample scripts would go a long way.

**Comment by ovalhub** [comment]
> On Mar 18, 2016, at 19:37, Tyler Crompton <notifications@github.com> wrote:
> 
> Having a few simple, non-exhaustive sample scripts would go a long way.
> 
There are some examples in README.md and in the tests directory.

Andi..

**Comment by ovalhub** [comment]
> On Mar 18, 2016, at 19:35, Tyler Crompton <notifications@github.com> wrote:
> 
> It would help if the wrappers at least had docstrings. Since some things are missing and others have been changed, it'd be helpful to have some docstrings. Even using the ICU documentation, I can't figure out what I'm doing. I am by no means new to programming or using Unicode.
> 
How about adding the docstrings you wish you had while figuring things out from the source code and the ICU docs ? It's a great way to learn the api and to write useful docstrings that don't state the obvious.
Patches welcome !

Andi..

**Comment by Apsod** [comment]
It would also be helpful to have a list or outline detailing which parts of the API that have been implemented and not.
A non-obvious mapping between your API and the original, no documentation, and partial implementation have so far been a perfect storm of user frustration.

**Comment by ovalhub** [comment]
> On Jun 28, 2016, at 07:07, Apsod <notifications@github.com> wrote:
> 
> It would also be helpful to have a list or outline detailing which parts of the API that have been implemented and not.
> A non-obvious mapping between your API and the original, no documentation, and partial implementation have so far been a perfect storm of user frustration.
> 
Read the code, it has what you're looking for.
If you see something missing that you want wrapped, ask. If you have something positive to contribute, in terms of documentation, examples, or new wrappers please do.
This is open source, scratch your itch. Complaining about it is not getting you anywhere.

Andi..

**Comment by ovalhub** [comment]
Note that documentation and samples can be added to icu/docs.py. Patches welcome.
