### ISSUE TITLE
::id rule specifies an unknown transliterator when creating Transliterator.

### ISSUE THREAD

**Issue by AntoJvlt** [ovalhub/pyicu#142]
Hello,

I encounter an error when trying to create an instance of Transliterator with a compound IDs rule:
The final rule that I want to use is:
`:: NFD (); [[:Nonspacing Mark:] [:Cf:]] >;  :: lower (); [[:Punctuation:][:Space:]]+ > ' '; :: NFC ();`

When I do: `Transliterator.createInstance(":: NFD (); [[:Nonspacing Mark:] [:Cf:]] >;  :: lower (); [[:Punctuation:][:Space:]]+ > ' '; :: NFC ();")`

I get the error: `icu.ICUError: A '::id' rule specifies an unknown transliterator, error code: 65569`

Following [ICU documentation](http://userguide.icu-project.org/transforms/general) this rule should works.

I tried to decompose the rule in order to find what transliterator id makes an error.

It seems that the syntax with `::` creates an error, so this rule works:
`NFD (); lower (); NFC ();`

And the replacement operator `>` creates an error too, so this rule works:
`NFD (); [[:Nonspacing Mark:] [:Cf:]] >;  lower (); NFC ();`

But this seems quite problematic as I need to keep my original rule because it is also used by PHP's Transliterator object.

Is that a normal behavior in PyICU like not supporting some rules from original ICU or it is my mistake?

Thanks.

**Comment by ovalhub** [comment]
> On Mar 21, 2021, at 09:32, Antonin ***@***.***> wrote:
> 
> ﻿
> Hello,
> 
> I encounter an error when trying to create an instance of Transliterator with a compound IDs rule:
> The final rule that I want to use is:
> :: NFD (); [[:Nonspacing Mark:] [:Cf:]] >; :: lower (); [[:Punctuation:][:Space:]]+ > ' '; :: NFC ();
> 
> When I do: Transliterator.createInstance(":: NFD (); [[:Nonspacing Mark:] [:Cf:]] >; :: lower (); [[:Punctuation:][:Space:]]+ > ' '; :: NFC ();")
> 
> I get the error: icu.ICUError: A '::id' rule specifies an unknown transliterator, error code: 65569
> 
> Following ICU documentation this rule should works.
> 
> I tried to decompose the rule in order to find what transliterator id makes an error.
> 
> It seems that the syntax with :: creates an error, so this rule works:
> NFD (); lower (); NFC ();
> 
> And the replacement operator > creates an error too, so this rule works:
> NFD (); [[:Nonspacing Mark:] [:Cf:]] >; lower (); NFC ();
> 
> But this seems quite problematic as I need to keep my original rule because it is also used by PHP's Transliterator object.
> 
> Is that a normal behavior in PyICU like not supporting some rules from original ICU or it is my mistake?
> 
PyICU is just a wrapper around ICU so I don't expect it to do anything differently with transliterator rules. Maybe you're not running the same versions of ICU from php than from python ? You didn't say either way.
Given that you're getting an ICU error, I'd recommend asking the same question on the ICU support mailing list, specifying the version number if ICU you're using.

**Comment by ovalhub** [comment]
Maybe you're using the wrong Transliterator method ?
This call seems to work fine:

Transliterator.createFromRules("some_id", ":: NFD (); [[:Nonspacing Mark:] [:Cf:]] >;  :: lower (); [[:Punctuation:][:Space:]]+ > ' '; :: NFC ();")

Andi..

**Comment by AntoJvlt** [comment]
Thanks you very much, that's totally my bad, I tried this function but with wrong first argument "id".

It is working, Thanks.
