### ISSUE TITLE
Fails to build with icu68

### ISSUE THREAD

**Issue by rmcgibbo** [ovalhub/pyicu#143]
Hi,

I noticed that this package builds fine against libuci 67.1, but fails to build with icu 68.2.

Here's a relevant build log:
https://nix-cache.s3.amazonaws.com/log/s8qisnliz4djqiywzz0pa9q5l25q8yw1-python3.9-PyICU-2.3.1.drv

**Comment by ovalhub** [comment]
That's correct. To build PyICU against ICU 68 you need the most recent version of PyICU itself, you seem to be using 2.3.1 here.

Andi..

**Comment by rmcgibbo** [comment]
Oh, thanks. I will update pyicu instead. I believe I got confused because I didn't see any tags on git.

Thanks for the advice!
