### ISSUE TITLE
Can't install on Linux

### ISSUE THREAD

**Issue by mayhewsw** [ovalhub/pyicu#15]
I'm having trouble installing pyicu. I've tried to install with pip, and install from source, but each time I get this error (run: python setup.py build): 

```
shape.cpp: In function ‘void _init_shape(PyObject*)’:
shape.cpp:167: error: ‘U_SHAPE_TAIL_NEW_UNICODE’ was not declared in this scope
shape.cpp:168: error: ‘U_SHAPE_TAIL_TYPE_MASK’ was not declared in this scope
/usr/include/unicode/tmutfmt.h: At global scope:
/usr/include/unicode/tmutfmt.h:231: warning: ‘UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)’ declared ‘static’ but never defined
error: command 'gcc' failed with exit status 1

```

I'm using Scientific Linux 6.7 (Carbon), python 2.7

**Comment by ovalhub** [comment]
On Mon, 8 Feb 2016, Stephen Mayhew wrote:

> I'm having trouble installing pyicu. I've tried to install with pip, and install from source, but each time I get this error (run: python setup.py build):
>
> ```
> shape.cpp: In function ?void _init_shape(PyObject*)?:
> shape.cpp:167: error: ?U_SHAPE_TAIL_NEW_UNICODE? was not declared in this scope
> shape.cpp:168: error: ?U_SHAPE_TAIL_TYPE_MASK? was not declared in this scope
> /usr/include/unicode/tmutfmt.h: At global scope:
> /usr/include/unicode/tmutfmt.h:231: warning: ?UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)? declared ?static? but never defined
> error: command 'gcc' failed with exit status 1

Both of these were added in ICU 4.8. If you're installing against an ICU 
version older than 4.8, you've hit a bug as these should be guarded by an
#if on that version.

What version of ICU are you building against ?
I just submitted a change in shape.cpp that adds the missing #if version 
guards for older versions of ICU (pre 4.2 and pre 4.8).

Andi..

**Comment by mayhewsw** [comment]
OK. `locate icu` shows that I'm probably using version 4.2.1. I'll see about upgrading! Thanks.
