### ISSUE TITLE
build problem: missing icu/common/unicode/ headers

### ISSUE THREAD

**Issue by conjugateprior** [ovalhub/pyicu#32]
Just compiled and installed the most recent ICU (58 http://site.icu-project.org/download/58) on a Centos 5 machine and tried to compile the PyICU 1.9.3 from https://pypi.python.org/pypi/PyICU/ and also the master from GitHub. Same error for both:

> [iccdb@web80 pyicu-master]$ python setup.py build
running build
running build_py
creating build
creating build/lib.linux-i686-2.7
copying icu.py -> build/lib.linux-i686-2.7
copying PyICU.py -> build/lib.linux-i686-2.7
copying docs.py -> build/lib.linux-i686-2.7
running build_ext
building '_icu' extension
creating build/temp.linux-i686-2.7
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include/python2.7 -c _icu.cpp -o build/temp.linux-i686-2.7/_icu.o -DPYICU_VER="1.9.3"
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
In file included from _icu.cpp:27:
common.h:102:28: error: unicode/udatpg.h: No such file or directory
common.h:103:30: error: unicode/dtptngen.h: No such file or directory
error: command 'gcc' failed with exit status 1

`udatpg.h` and `dtptngen.h` are in `i18n/unicode/` down in the icu source, but they don't seem to make it into the `make install`ed include directory (below)
 
For reference, this is python 2.7.12, with a local icu stuff in `/home/me/lib` and `/home/me/include`, which also went into the `setup.py`.

Is there perhaps a less recent ICU that is known to work better?

**Comment by ovalhub** [comment]
On Tue, 1 Nov 2016, Will Lowe wrote:

> Just compiled and installed the most recent ICU (58 http://site.icu-project.org/download/58) on a Centos 5 machine and tried to compile the PyICU 1.9.3 from https://pypi.python.org/pypi/PyICU/ and also the master from GitHub. Same error for both:
>
>> [iccdb@web80 pyicu-master]$ python setup.py build
> running build
> running build_py
> creating build
> creating build/lib.linux-i686-2.7
> copying icu.py -> build/lib.linux-i686-2.7
> copying PyICU.py -> build/lib.linux-i686-2.7
> copying docs.py -> build/lib.linux-i686-2.7
> running build_ext
> building '_icu' extension
> creating build/temp.linux-i686-2.7
> gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include/python2.7 -c _icu.cpp -o build/temp.linux-i686-2.7/_icu.o -DPYICU_VER="1.9.3"
> cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
> In file included from _icu.cpp:27:
> common.h:102:28: error: unicode/udatpg.h: No such file or directory
> common.h:103:30: error: unicode/dtptngen.h: No such file or directory
> error: command 'gcc' failed with exit status 1
>
> It's not kidding either. `udatpg.h` and `dtptngen.h` are not in `icu/common/unicode` down in the icu source.

Well, maybe these files don't exist in ICU 58. I've not yet built PyICU with
ICU 58. The latest I've built it with is ICU 57.1.

I'd suggest reverting to 57.x or adding conditionals around the failing 
parts.

Andi..

**Comment by conjugateprior** [comment]
Thanks, I'll pull back a version.  

I'd guess layout engine changes will probably be the main change in 58 to cause trouble.

**Comment by conjugateprior** [comment]
For future readers, my writeup above is actually mistaken. When platform issues are fixed the main problem is elsewhere (in `layoutengine.cpp`), but not worth another ticket because I'm pulling back to ICU 57 anyway.

**Comment by ovalhub** [comment]
this is now fixed in version 1.9.4, ICU 58.1 is supported
