### ISSUE TITLE
error when try to run ImportError: /usr/local/lib/python3.5/dist-packages/_icu.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTIN6icu_5714LEFontInstanceE

### ISSUE THREAD

**Issue by bilalbayasut** [ovalhub/pyicu#37]
I got this error when I tried to run my code

ImportError: /usr/local/lib/python3.5/dist-packages/_icu.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTIN6icu_5714LEFontInstanceE

any ideas?

**Comment by ovalhub** [comment]
> On Nov 11, 2016, at 00:37, Bilal Luqman Bayasut <notifications@github.com> wrote:
> 
> I got this error when I tried to run my code
> 
> ImportError: /usr/local/lib/python3.5/dist-packages/_icu.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTIN6icu_5714LEFontInstanceE
> 
> any ideas?
> 
What do these commands return ?
  $ icu-config --version
  $ which icu-config
Which version of PyICU are you using ?

Andi..

**Comment by joejnke** [comment]
So, what is the suggested solution?

**Comment by ovalhub** [comment]
> On Aug 20, 2018, at 05:17, joejnke <notifications@github.com> wrote:
> 
> So, what is the suggested solution?
> 
Ensure you have only one version of ICU on your system or use the same for compiling, linking and running PyICU.

Andi..
