### ISSUE TITLE
PyICU-1.9.5 fails to compile on Python 3.x / Windows

### ISSUE THREAD

**Issue by cgohlke** [ovalhub/pyicu#38]
Using icu-58.1 and msvc10/14, PyICU-1.9.5 fails to compile on CPython 3.x:
```
common.cpp(226): error C2664: 'UChar *u_memcpy_58(UChar *,const UChar *,int32_t)': cannot convert argument 1 from 'Py_UCS2 *' to 'UChar *'
```

PyICU-1.9.4 compiled OK.

**Comment by ovalhub** [comment]
> On Nov 11, 2016, at 14:25, Christoph Gohlke <notifications@github.com> wrote:
> 
> Using icu-58.1 and msvc10/14, PyICU-1.9.5 fails to compile on CPython 3.x:
> 
> common.cpp(226): error C2664: 'UChar *u_memcpy_58(UChar *,const UChar *,int32_t)': cannot convert argument 1 from 'Py_UCS2 *' to 'UChar *'
> PyICU-1.9.4 compiled OK.
> 
I don't have a Windows system to try this on but adding a cast to (UChar *) should fix the problem.

Please, let me know if this solves it.
Thanks !

Andi..

**Comment by cgohlke** [comment]
> I don't have a Windows system to try this on but adding a cast to (UChar *) should fix the problem.

It does. Thanks.
