### ISSUE TITLE
No such file or directory: 'README.md'

### ISSUE THREAD

**Issue by dsblank** [ovalhub/pyicu#4]
Our travis just broke on:
```
$ travis_retry sudo pip3 install pyicu
Collecting pyicu
  Downloading PyICU-1.9.tar.gz (175kB)
    100% |████████████████████████████████| 176kB 1.9MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-8u4vam/pyicu/setup.py", line 88, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by ovalhub** [comment]
On Sat, 9 May 2015, Doug Blank wrote:

> Our travis just broke on:
> ```
> $ travis_retry sudo pip3 install pyicu
> Collecting pyicu
>  Downloading PyICU-1.9.tar.gz (175kB)
>    100% |????????????????????????????????| 176kB 1.9MB/s
>    Complete output from command python setup.py egg_info:
>    Traceback (most recent call last):
>      File "<string>", line 20, in <module>
>      File "/tmp/pip-build-8u4vam/pyicu/setup.py", line 88, in <module>
>        long_description=open('README.md').read(),
>    IOError: [Errno 2] No such file or directory: 'README.md'
> ```

Thank you for letting me know.
It turned out there were several missing things in that 1.9 release package.
I added a MANIFEST.in file that seems to have fixed this and released 1.9.1
on PyPI: https://pypi.python.org/pypi/PyICU/1.9.1

Andi..

**Comment by dsblank** [comment]
Thanks!

**Comment by dsblank** [comment]
Still won't build, though:

https://travis-ci.org/gramps-project/gramps/builds/61920436

**Comment by ovalhub** [comment]
> On May 9, 2015, at 18:06, Doug Blank <notifications@github.com> wrote:
> 
> Still won't build, though:
> 
> https://travis-ci.org/gramps-project/gramps/builds/61920436
> 
I scrolled and scrolled but see no compile errors, only lots of warnings. What's the actual error ?

I did a test build of the result of 'sdist' and it built on my end (icu 55.1, mac osx 10.10.3, python 2.7.5 and others).
(I should fix the writable-strings thing, so much noise)

Andi..

**Comment by dsblank** [comment]
Looks like:

```
 char.cpp:692:22: error: ‘u_getBidiPairedBracket’ was not declared in this scope
```

**Comment by ovalhub** [comment]
On Sat, 9 May 2015, Doug Blank wrote:

> Looks like:
>
> ```
> char.cpp:692:22: error: ?u_getBidiPairedBracket? was not declared in this scope
> ```

Ah, yes, that one appeared in ICU 52. What's your version of ICU ?
Still, the bug is on my end, it should be conditionally enabled...

Andi..

**Comment by ovalhub** [comment]
On Sat, 9 May 2015, Doug Blank wrote:

> Looks like:
>
> ```
> char.cpp:692:22: error: ?u_getBidiPairedBracket? was not declared in this scope
> ```

Can you please patch that in:
   https://github.com/ovalhub/pyicu/commit/0fbd3d18d38d0dab1623e05676f84c2d072ed704
and give it another try ?
Once you have a successful build, I can release 1.9.2 with all the fixes.

(no, I don't test on all OSs and with all versions of ICU around)

Andi..

**Comment by dsblank** [comment]
You should use Travis/Jenkins Continuous Integration. They run automatically on each commit.

I'd have to go change our travis to test in the original environment.

I tried on my home machine and got this error:
```
dateformat.cpp:1690:50: error: ‘UDISPCTX_LENGTH_FULL’ was not declared in this scope
     INSTALL_ENUM(UDisplayContext, "LENGTH_FULL", UDISPCTX_LENGTH_FULL);
                                                  ^
macros.h:356:57: note: in definition of macro ‘INSTALL_ENUM’
                          make_descriptor(PyInt_FromLong(value)))
                                                         ^
dateformat.cpp:1691:51: error: ‘UDISPCTX_LENGTH_SHORT’ was not declared in this scope
     INSTALL_ENUM(UDisplayContext, "LENGTH_SHORT", UDISPCTX_LENGTH_SHORT);
                                                   ^
macros.h:356:57: note: in definition of macro ‘INSTALL_ENUM’
                          make_descriptor(PyInt_FromLong(value)))
                                                         ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by ovalhub** [comment]
On Sat, 9 May 2015, Doug Blank wrote:

> You should use Travis/Jenkins Continuous Integration. They run 
> automatically on each commit.

I've never heard of Travis, thanks for pointing it out.
They'll run on all versions of ICU around ?

> I'd have to go change our travis to test in the original environment.
>
> I tried on my home machine and got this error:
> ```
> dateformat.cpp:1690:50: error: ?UDISPCTX_LENGTH_FULL? was not declared in this scope
>     INSTALL_ENUM(UDisplayContext, "LENGTH_FULL", UDISPCTX_LENGTH_FULL);
>                                                  ^
> macros.h:356:57: note: in definition of macro ?INSTALL_ENUM?
>                          make_descriptor(PyInt_FromLong(value)))
>                                                         ^
> dateformat.cpp:1691:51: error: ?UDISPCTX_LENGTH_SHORT? was not declared in this scope
>     INSTALL_ENUM(UDisplayContext, "LENGTH_SHORT", UDISPCTX_LENGTH_SHORT);
>                                                   ^
> macros.h:356:57: note: in definition of macro ?INSTALL_ENUM?
>                          make_descriptor(PyInt_FromLong(value)))

Indeed. These two appeared in ICU 54.
Ok, I added a new conditional around them (was at 51, needs to be at 54).

It's fixed in 
https://github.com/ovalhub/pyicu/commit/4737a6d7f64c703660e7456c8744987cdc85d3a6

I also fixed all the writable-strings warnings I could find (PyICU-wide).

Please, let me know if you've got a successful build now ?
Thanks !

Andi..

**Comment by dsblank** [comment]
Great, thanks... it builds now! Both with python and python3.

I did need to install this first: `sudo apt-get install libicu-dev`

**Comment by ovalhub** [comment]
On Sat, 9 May 2015, Doug Blank wrote:

> Great, thanks... it builds now! Both with python and python3.

Yay !

> I did need to install this first: `sudo apt-get install libicu-dev`

Yes, you do need the ICU include files to build.

Thank you for your time.
I'll release 1.9.2 next to PyPI.

Andi..
