### ISSUE TITLE
setup.py fails on Python 2.6

### ISSUE THREAD

**Issue by SethMMorton** [ovalhub/pyicu#40]
I am not sure if PyICU is intended to support Python 2.6; if not please close this issue.

If you do intend to support Python 2.6, the call to `subprocess.check_output` in `setup.py` fails because `check_output` was not added till Python 2.7.

     File "/tmp/pip-build-wPhmnv/PyICU/setup.py", line 11, in <module>
        ICU_VERSION = subprocess.check_output(('icu-config', '--version')).strip()
    AttributeError: 'module' object has no attribute 'check_output'

**Comment by SethMMorton** [comment]
I confirm this works for me.  Thanks!

Will this be released as a patch soon, or do I need to use a custom build?

**Comment by ovalhub** [comment]
On Mon, 2 Jan 2017, Seth Morton wrote:

> I confirm this works for me.  Thanks!
>
> Will this be released as a patch soon, or do I need to use a custom build?

Thank you for verifying this.
You need a custom build for the time being...

Andi..
