### ISSUE TITLE
setup.py fails on windows du to no icu-config binary

### ISSUE THREAD

**Issue by amynbe** [ovalhub/pyicu#44]
The following line: 

ICU_VERSION = subprocess.check_output(('icu-config', '--version')).strip()

( https://github.com/ovalhub/pyicu/commit/81830b36d85c12bcab959dce4d9f4332cb9ec6bc#diff-2eeaed663bd0d25b7e608891384b7298R11 )

Fails on windows for which an icu-config exe doesn't exist (the icu win binaries include a bunch of dll and exe files but no icu-config).

**Comment by ovalhub** [comment]
If you don't have that executable installed or findable vis PATH, plug the version of ICU version you hsve installed into the ICU_VERSION variable in place of the subprocess icu_config call.

Andi..

**Comment by amynbe** [comment]
Hi Andi,
Thanks for the answer. A windows distribution of icu-config doesn't exist, so I think this needs a code fix. Installation through pip is broken at the moment.

**Comment by ovalhub** [comment]
I think someone else had this issue on Windows and realized they hadn't installed icu-config. I don't have Windows to try this out. Please, ask on the ICU list what the deal is with icu-config on Windows and let me know what they say.

Thanks !

Andi..

**Comment by amynbe** [comment]
After a long internet search I'm pretty sure there's no icu-config for windows. 
However there's `uconv -V`:
http://stackoverflow.com/questions/26733346/how-to-know-what-version-of-icu-comes-with-an-os

**Comment by amynbe** [comment]
Asked on the list -- no answer https://sourceforge.net/p/icu/mailman/icu-support/thread/CAJ%3DfZjP_8NyR_iLiQOVf3djfaJUyOvgKpG%2Bbbhzyz8zm2iL7fA%40mail.gmail.com/#msg35702166

**Comment by ovalhub** [comment]
> On Mar 8, 2017, at 18:05, Amyn <notifications@github.com> wrote:
> 
> Asked on the list -- no answer https://sourceforge.net/p/icu/mailman/icu-support/thread/CAJ%3DfZjP_8NyR_iLiQOVf3djfaJUyOvgKpG%2Bbbhzyz8zm2iL7fA%40mail.gmail.com/#msg35702166
> 
Thank you, I asked some ICU devs and they didn't "think so" as they don't use Windows.
I'm going to change the logic in setup.py so that it checks for an ICU_VERSION env variable first and only calls icu-config if that env var is not set.
In the meantime, please edit setup.py to force the correct value into its ICU_VERSION var.

Andi..

**Comment by ovalhub** [comment]
Added check for an ICU_VERSION environment variable to be set before calling icu-config.
Added an error message asking for ICU_VERSION env var to be set when calling icu-config fails.
