### ISSUE TITLE
testSurrogatePairs failure on Cygwin

### ISSUE THREAD

**Issue by wilx** [ovalhub/pyicu#55]
I am seeing the following test failure on Cygwin with Python 3.

```
======================================================================
FAIL: testSurrogatePairs (test.test_Script.TestScript)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/cygdrive/c/stuff/PyICU-1.9.7/test/test_Script.py", line 48, in testSurrogatePairs
    self.assertEqual(['Latn', 'Deva', 'Hani', 'Hani', 'Hani'], names)
AssertionError: Lists differ: ['Latn', 'Deva', 'Hani', 'Hani', 'Hani'] != ['Latn', 'Deva', 'Hani', 'Zzzz', 'Zzzz']

First differing element 3:
'Hani'
'Zzzz'

- ['Latn', 'Deva', 'Hani', 'Hani', 'Hani']
?                           ^^^^    ^^^^

+ ['Latn', 'Deva', 'Hani', 'Zzzz', 'Zzzz']
?                           ^^^^    ^^^^


----------------------------------------------------------------------
Ran 39 tests in 0.428s

FAILED (failures=1)
Test failed: <unittest.runner.TextTestResult run=39 errors=0 failures=1>
error: Test failed: <unittest.runner.TextTestResult run=39 errors=0 failures=1>
```

This is with PyICU 1.9.7 for ICU 58.2, Python 3.6.1.

**Comment by ovalhub** [comment]
what version of ICU ?
what version of Python ?

**Comment by wilx** [comment]
[**@ovalhub**](https://github.com/ovalhub) commented on [24. 5. 2017 16:39 SELČ](https://github.com/ovalhub/pyicu/issues/55#issuecomment-303744642 "2017-05-24T14:39:58Z - Replied by Github Reply Comments"):
> <div class="email-fragment">what version of ICU ?
> what version of Python ?</div>

The information is at the bottom of the OP: This is with PyICU 1.9.7 for ICU 58.2, Python 3.6.1.

**Comment by ovalhub** [comment]
nope, the email I received only mentions PyICU 1.9.7
I can see you're on Cygwin from the paths mentioned, nothing else.

Anyhow, I don't have access to Windows so there isn't much I can do to debug this. It may be the case that some conditional code is missing for the cygwin platform you added recently. See the code that converts between icu unicode and python strings for attempting to debug it.

Let me know what you find out...

Andi..

**Comment by wilx** [comment]
So I have been debugging this and this is what I got so far. It seems to me this is somehow related either to how `UnicodeString` objects are being iterated over in Python or ICU and possible change of behaviour.

I have instrumented the module source with some debugging prints:

```
before pairs = UnicodeString(pairs)
icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&)
icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&): 4BYTE kind
icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&): PyUnicode_GET_LENGTH(object): 4
pairs: aॐ中𩻺
len(pairs):  5
PyObject* t_script_getScript(PyTypeObject*, PyObject*)
icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&)
icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&): 1BYTE kind
PyObject* t_script_getScript(PyTypeObject*, PyObject*): S
PyObject* t_script_getScript(PyTypeObject*, PyObject*): u->char32At(0): 61
PyObject* t_script_getScript(PyTypeObject*, PyObject*): code: 25
PyObject* t_script_getScript(PyTypeObject*, PyObject*)
icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&)
icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&): 2BYTE kind
PyObject* t_script_getScript(PyTypeObject*, PyObject*): S
PyObject* t_script_getScript(PyTypeObject*, PyObject*): u->char32At(0): 950
PyObject* t_script_getScript(PyTypeObject*, PyObject*): code: 10
PyObject* t_script_getScript(PyTypeObject*, PyObject*)
icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&)
icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&): 2BYTE kind
PyObject* t_script_getScript(PyTypeObject*, PyObject*): S
PyObject* t_script_getScript(PyTypeObject*, PyObject*): u->char32At(0): 4e2d
PyObject* t_script_getScript(PyTypeObject*, PyObject*): code: 17
PyObject* t_script_getScript(PyTypeObject*, PyObject*)
icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&)
icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&): 2BYTE kind
PyObject* t_script_getScript(PyTypeObject*, PyObject*): S
PyObject* t_script_getScript(PyTypeObject*, PyObject*): u->char32At(0): d867
PyObject* t_script_getScript(PyTypeObject*, PyObject*): code: 103
PyObject* t_script_getScript(PyTypeObject*, PyObject*)
icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&)
icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&): 2BYTE kind
PyObject* t_script_getScript(PyTypeObject*, PyObject*): S
PyObject* t_script_getScript(PyTypeObject*, PyObject*): u->char32At(0): defa
PyObject* t_script_getScript(PyTypeObject*, PyObject*): code: 103
after names = [Script.getScript(cp).getShortName() for cp in pairs]
```

As you can see, we get `u->char32At(0): d867` and `u->char32At(0): defa` in `t_script_getScript()`, both of the surrogates, and ICU returns script code 103 which is a code for unknown script.

To verify, I have also used the following C++ source:

```cpp
#include <iostream>
#include <iomanip>
#include <unicode/uscript.h>

void test (UChar32 codepoint)
{
    UErrorCode err = UErrorCode();
    std::cout << "tested code point: U+"
              << std::hex << codepoint << std::dec << "\n";
    UScriptCode script_code = uscript_getScript(codepoint, &err);
    std::cout << "script code: " << script_code << "\n"
              << "err: " << err << "\n";
}

int
main ()
{
    UChar32 const code_points[5] = {
        0x61, 0x950, 0x4e2d, 0xd867, 0xdefa
    };

    for (auto cp : code_points)
    {
        test(cp);
        std::cout << "\n";
    }
}
```

**Comment by ovalhub** [comment]
On Fri, 26 May 2017, Václav Haisman wrote:

> So I have been debugging this and this is what I got so far. It seems to me this is somehow related either to how `UnicodeString` objects are being iterated over in Python or ICU and possible change of behaviour.
>
> I have instrumented the module source with some debugging prints:
>
> ```
> before pairs = UnicodeString(pairs)
> icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&)
> icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&): 4BYTE kind
> icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&): PyUnicode_GET_LENGTH(object): 4
> pairs: a???
> len(pairs):  5
> PyObject* t_script_getScript(PyTypeObject*, PyObject*)
> icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&)
> icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&): 1BYTE kind
> PyObject* t_script_getScript(PyTypeObject*, PyObject*): S
> PyObject* t_script_getScript(PyTypeObject*, PyObject*): u->char32At(0): 61
> PyObject* t_script_getScript(PyTypeObject*, PyObject*): code: 25
> PyObject* t_script_getScript(PyTypeObject*, PyObject*)
> icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&)
> icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&): 2BYTE kind
> PyObject* t_script_getScript(PyTypeObject*, PyObject*): S
> PyObject* t_script_getScript(PyTypeObject*, PyObject*): u->char32At(0): 950
> PyObject* t_script_getScript(PyTypeObject*, PyObject*): code: 10
> PyObject* t_script_getScript(PyTypeObject*, PyObject*)
> icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&)
> icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&): 2BYTE kind
> PyObject* t_script_getScript(PyTypeObject*, PyObject*): S
> PyObject* t_script_getScript(PyTypeObject*, PyObject*): u->char32At(0): 4e2d
> PyObject* t_script_getScript(PyTypeObject*, PyObject*): code: 17
> PyObject* t_script_getScript(PyTypeObject*, PyObject*)
> icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&)
> icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&): 2BYTE kind
> PyObject* t_script_getScript(PyTypeObject*, PyObject*): S
> PyObject* t_script_getScript(PyTypeObject*, PyObject*): u->char32At(0): d867
> PyObject* t_script_getScript(PyTypeObject*, PyObject*): code: 103
> PyObject* t_script_getScript(PyTypeObject*, PyObject*)
> icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&)
> icu_58::UnicodeString& PyObject_AsUnicodeString(PyObject*, const char*, const char*, icu_58::UnicodeString&): 2BYTE kind
> PyObject* t_script_getScript(PyTypeObject*, PyObject*): S
> PyObject* t_script_getScript(PyTypeObject*, PyObject*): u->char32At(0): defa
> PyObject* t_script_getScript(PyTypeObject*, PyObject*): code: 103
> after names = [Script.getScript(cp).getShortName() for cp in pairs]
> ```
>
> As you can see, we get `u->char32At(0): d867` and `u->char32At(0): defa` in `t_script_getScript()`, both of the surrogates, and ICU returns script code 103 which is a code for unknown script.
>
> To verify, I have also used the following C++ source:
>
> ```cpp
> #include <iostream>
> #include <iomanip>
> #include <unicode/uscript.h>
>
> void test (UChar32 codepoint)
> {
>    UErrorCode err = UErrorCode();
>    std::cout << "tested code point: U+"
>              << std::hex << codepoint << std::dec << "\n";
>    UScriptCode script_code = uscript_getScript(codepoint, &err);
>    std::cout << "script code: " << script_code << "\n"
>              << "err: " << err << "\n";
> }
>
> int
> main ()
> {
>    UChar32 const code_points[5] = {
>        0x61, 0x950, 0x4e2d, 0xd867, 0xdefa
>    };

That code_points array doesn't look right.
Shouldn't it be { 0x61, 0x950, 0x4e2d, 0x00029efa } ?

Andi..

**Comment by wilx** [comment]
> That code_points array doesn't look right. Shouldn't it be { 0x61, 0x950, 0x4e2d, 0x00029efa } ? 

Well, the loop iterates over 5 items, last two of them are the two parts of surrogate pair. I do not know what is the intended behaviour for iteration over `UnicodeString`. Is it supposed to iterate over its `UChar16` units or over Unicode code points?

**Comment by ovalhub** [comment]
It depends how you iterate: using next() or next32() (whatever the actual names are, check the icu docs)

Andi..

**Comment by wilx** [comment]
> It depends how you iterate: using next() or next32() (whatever the actual names are, check the icu docs)

It seems the code of the test case actually expects more script info items than there are characters. There are 4 characters (aॐ中𩻺) but the test case expects 5 items. That suggests to me that it expects to iterate over the individual surrogates of the surrogate pairs. But ICU returns unknown script for the individual surrogates of the surrogate pair.

So, the question is, **how is `UnicodeString` supposed to be iterated over in Python? Over individual UChar16 bits or over Unicode code points?**

**Comment by ovalhub** [comment]
On Mon, 29 May 2017, Václav Haisman wrote:

> It seems the code of the test case actually expects more script info items 
> than there are characters. There are 4 characters (a???) but the test case 
> expects 5 items. That suggests to me that it expects to iterate over the 
> individual surrogates of the surrogate pairs. But ICU returns unknown 
> script for the individual surrogates of the surrogate pair.
>
> So, the question is, **how is `UnicodeString` supposed to be iterated over 
> in Python? Over individual UChar16 bits or over Unicode code points?**

Typically, one doesn't iterate an ICU UnicodeString in PyICU since PyICU 
always converts the ICU UnicodeString into a native Python string before 
returning it.
If you force a UnicodeString to be returned, then Python sees it as sequence
and it can be iterated that way. Note that I just noticed a bug in the 
UnicodeString-as-sequence code when surrogate pairs are involved. The intent 
is to iterate 16-bit UChar, not codepoints, so I need to fix this.
(to iterate codepoints, iterate the corresponding Python string)
For example:
   >>> a=UnicodeString(u'\U0001f600')
   >>> a
   <UnicodeString: '\U0001f600'>
   >>> a.length()
   2  <--- correct since ICU returns the number of UChar in its string
   >>> list(a)
   ['\U0001f600', '\U0001f600']  <--- bad, the 16-bit UChar should be returned
   >>> str(a)
   '\U0001f600'
   >>> len(str(a))
   1  <--- correct

I should have a fix shortly.

**Comment by ovalhub** [comment]
I just commited a fix for the bug found when iterating UnicodeString objects (as opposed to Python strings). Fixing this revealed the bug you first reported here in test_Script.py.
When iterating the UnicodeString('a\u0950\u4e2d\U00029efa') one should get 5 UChar:
  ['a', '\u0950', '\u4e2d', '\ud867', '\udefa']
whose script names are
  ['Latn', 'Deva', 'Hani', 'Zzzz', 'Zzzz']
Thank you for your bug report here, it was a bit tricky getting to the bottom of it and I hope it fixes it too on cygwin. Please, let me know and I'll close the issue as resolved once you confirm it fixed.

**Comment by wilx** [comment]
The tests pass on revision 607b074d671d3a09761ee5867355eee8cd31191a on Cygwin.

**Comment by ovalhub** [comment]
closing, thanks !
