### ISSUE TITLE
compact currency formatting

### ISSUE THREAD

**Issue by ziyadm** [ovalhub/pyicu#57]
this isn't an issue per-se; i was just curious whether you had any examples of how to do compact currency formatting. for instance, formatting 1234 US dollars as $1.2K.

a pointer to how to do something to that effect would be great @ovalhub. happy to chat offline/not in this issue as well

**Comment by ovalhub** [comment]
On Mon, 24 Jul 2017, Ziyad Mir wrote:

> this isn't an issue per-se; i was just curious whether you had any 
> examples of how to do compact currency formatting. for instance, 
> formatting 1234 US dollars as $1.2K.
>
> a pointer to how to do something to that effect would be great @ovalhub. 
> happy to chat offline/not in this issue as well

Docs are here:
   http://icu-project.org/apiref/icu4c/classicu_1_1NumberFormat.html
For example:
  >>> from icu import *
  >>> f = CompactDecimalFormat.createCurrencyInstance(Locale.getUS())
  >>> f.format(1234)
  u'$1,234.00'

Andi..

**Comment by ziyadm** [comment]
Sorry,  it sure I totally understand @ovalhub -- how do I use that to format the compact version of the currency?

**Comment by ziyadm** [comment]
not sure ***

**Comment by ovalhub** [comment]
On Mon, 24 Jul 2017, Ziyad Mir wrote:

> Sorry,  it sure I totally understand @ovalhub -- how do I use that to format the compact version of the currency?

Did you see the example I included here:
   https://github.com/ovalhub/pyicu/issues/57

**Comment by ziyadm** [comment]
I see it, I just don't think I understand how to format the compact currency using that -- for instance, how do I format 1234 usd as $1.2k?

Maybe I'm not understanding what you are saying...

**Comment by ovalhub** [comment]
On Mon, 24 Jul 2017, Ziyad Mir wrote:

> I see it, I just don't think I understand how to format the compact 
> currency using that -- for instance, how do I format 1234 usd as $1.2k?
>
> Maybe I'm not understanding what you are saying...

Aaah, so you really want $1.2k, not $1,234 ?
I don't know how to do that but I'm sure it's possible.
Please, ask on the icu users mailing list.
