### ISSUE TITLE
Incompatibility with python 3.6

### ISSUE THREAD

**Issue by Thimxx** [ovalhub/pyicu#59]
According to this [issue in stackoverflow ](https://stackoverflow.com/questions/45526953/error-installing-pyicu-in-python-3-6-2-recently-installed-package)I understood that there are some incompatibilities between python 3.6 and PyICU, just reporting the error here so I can be fixed.

**Comment by ovalhub** [comment]
> On Aug 20, 2017, at 03:40, Thimxx <notifications@github.com> wrote:
> 
> According to this issue in stackoverflow I understood that there are some incompatibilities between python 3.6 and PyICU, just reporting the error here so I can be fixed.
> 
It looks like this is on Windows and you didn't set the ICU_VERSION environment variable to the ICU version you're using before starting the build ?

Andi..

**Comment by ovalhub** [comment]
And, just to confirm, PyICU works fine with Python 3.6. And yes, if ICU is not installed on your system, you must install it first.

Andi..
