### ISSUE TITLE
pyicu 1.9.7 tests fail with ICU 60.1

### ISSUE THREAD

**Issue by doko42** [ovalhub/pyicu#60]
LayoutEngine not available in ICU 60.1...............................F.......
======================================================================
FAIL: testGetSkeleton (test_Spoof.TestSpoofChecker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/build/py2/test/test_Spoof.py", line 62, in testGetSkeleton
    u" A long 'identifier' that vvill overflovv irnplernentation stack buffers, forcing heap allocations. A long 'identifier' that vvill overflovv irnplernentation stack buffers, forcing heap allocations. A long 'identifier' that vvill overflovv irnplernentation stack buffers, forcing heap allocations. A long 'identifier' that vvill overflovv irnplernentation stack buffers, forcing heap allocations.")
  File "/<<PKGBUILDDIR>>/build/py2/test/test_Spoof.py", line 55, in checkSkeleton
    self.assertEqual(skeleton, result)
AssertionError: u" A long 'identifier' that will overflow irnplernentation stack buffers, forcin [truncated]... != u" A long 'identifier' that vvill overflovv irnplernentation stack buffers, forc [truncated]...
Diff is 791 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 39 tests in 0.570s

FAILED (failures=1)

**Comment by ovalhub** [comment]
fixed in 1.9.8, just committed.
