### ISSUE TITLE
Thread safety?

### ISSUE THREAD

**Issue by jstasiak** [ovalhub/pyicu#63]
Hey,

I've been wondering - is it safe to share the object returned by ``icu.Transliterator.createInstance(...)`` between threads?

**Comment by ovalhub** [comment]
> On Dec 12, 2017, at 09:49, Jakub Stasiak <notifications@github.com> wrote:
> 
> Hey,
> 
> I've been wondering - is it safe to share the object returned by icu.Transliterator.createInstance(...) between threads?
> 

The python wrapper object ? sure. But can the wrapped C++ object be shared ? I don’t know, that’s a question for the icu users list. It may also be documented in the ICU docs.

Andi..

**Comment by ovalhub** [comment]
no comment
