### ISSUE TITLE
Error compiling PyICU 2.0 with ICU 52

### ISSUE THREAD

**Issue by mjansche** [ovalhub/pyicu#64]
I'm installing PyICU with pip in a Travis continuous build using Travis's Ubuntu "trusty" image, for which apt-get install libicu-dev installs ICU 52. The pip install of PyICU started failing today after the release of 2.0. Here is what I think is the relevant error message, taken from [the full log](https://api.travis-ci.org/v3/job/326775682/log.txt):

```
    In file included from measureunit.cpp:29:0:
    measureunit.cpp: In function â€˜int t_measure_init(t_measure*, PyObject*, PyObject*)â€™:
    measureunit.cpp:1686:70: error: cannot allocate an object of abstract type â€˜icu_52::Measureâ€™
                     Formattable(d), (MeasureUnit *) unit->clone(), status));
                                                                          ^
    macros.h:95:9: note: in definition of macro â€˜INT_STATUS_CALLâ€™
             action;                                                         \
             ^
    In file included from /usr/include/x86_64-linux-gnu/unicode/curramt.h:18:0,
                     from /usr/include/x86_64-linux-gnu/unicode/numfmt.h:39,
                     from /usr/include/x86_64-linux-gnu/unicode/datefmt.h:28,
                     from common.h:114,
                     from measureunit.cpp:24:
    /usr/include/x86_64-linux-gnu/unicode/measure.h:45:18: note:   because the following virtual functions are pure within â€˜icu_52::Measureâ€™:
     class U_I18N_API Measure: public UObject {
                      ^
    /usr/include/x86_64-linux-gnu/unicode/measure.h:77:22: note: 	virtual icu_52::UObject* icu_52::Measure::clone() const
         virtual UObject* clone() const = 0;
                          ^
```

In other words, [new Measure(...)](https://github.com/ovalhub/pyicu/blob/03d9f980fa96618e1674950965c957b7f21da977/measureunit.cpp#L1685) is not possible because icu_52::Measure is abstract, since its clone() method is pure virtual.

In [ICU 52-1](http://source.icu-project.org/repos/icu/icu/tags/release-52-1/source/i18n/unicode/measure.h) Measure::clone() was pure virtual. But starting from [ICU 53-1](http://source.icu-project.org/repos/icu/icu/tags/release-53-1/source/i18n/unicode/measure.h) Measure::clone() lost its purity.

This was never an issue with PyICU < 2. Any plans to support ICU 52 for PyICU?

**Comment by ovalhub** [comment]
> On Jan 9, 2018, at 14:29, Martin Jansche <notifications@github.com> wrote:
> 
> I'm installing PyICU with pip in a Travis continuous build using Travis's Ubuntu "trusty" image, for which apt-get install libicu-dev installs ICU 52. The pip install of PyICU started failing today after the release of 2.0. Here is what I think is the relevant error message, taken from the full log:
> 
>     In file included from measureunit.cpp:29:0:
>     measureunit.cpp: In function â€˜int t_measure_init(t_measure*, PyObject*, PyObject*)â€™:
>     measureunit.cpp:1686:70: error: cannot allocate an object of abstract type â€˜icu_52::Measureâ€™
>                      Formattable(d), (MeasureUnit *) unit->clone(), status));
>                                                                           ^
>     macros.h:95:9: note: in definition of macro â€˜INT_STATUS_CALLâ€™
>              action;                                                         \
>              ^
>     In file included from /usr/include/x86_64-linux-gnu/unicode/curramt.h:18:0,
>                      from /usr/include/x86_64-linux-gnu/unicode/numfmt.h:39,
>                      from /usr/include/x86_64-linux-gnu/unicode/datefmt.h:28,
>                      from common.h:114,
>                      from measureunit.cpp:24:
>     /usr/include/x86_64-linux-gnu/unicode/measure.h:45:18: note:   because the following virtual functions are pure within â€˜icu_52::Measureâ€™:
>      class U_I18N_API Measure: public UObject {
>                       ^
>     /usr/include/x86_64-linux-gnu/unicode/measure.h:77:22: note: 	virtual icu_52::UObject* icu_52::Measure::clone() const
>          virtual UObject* clone() const = 0;
>                           ^
> In other words, new Measure(...) is not possible because icu_52::Measure is abstract, since its clone() method is pure virtual.
> 
> In ICU 52-1 Measure::clone() was pure virtual. But starting from ICU 53-1 Measure::clone() lost its purity.
> 
> This was never an issue with PyICU < 2. Any plans to support ICU 52 for PyICU?
> 
That’s a bug. Building PyICU 2.0 with ICU 52 is supported. I do not test with such an old version of ICU - could you please confirm that this is the only build error with ICU 52 ? I can release 2.0.1 with a fix once you’ve confirmed it’s the only build error.
Just curious, why are you using such an old version of ICU ?

Thanks !

Andi.,.

**Comment by mjansche** [comment]
It's hard to tell if that's the only build error, since the build was aborted.

The reason I'm using a very old ICU is that this comes from a Travis continuous integration environment that is based on Ubuntu Trusty (14.04) whose [default prepackaged ICU](https://launchpad.net/ubuntu/+source/icu)  is version 52.

**Comment by ovalhub** [comment]
> On Jan 9, 2018, at 15:59, Martin Jansche <notifications@github.com> wrote:
> 
> It's hard to tell if that's the only build error, since the build was aborted.
> 
No, it’s very easy: just add an #if 0 / #endif bracket around the failing method and resume the build.
> The reason I'm using a very old ICU is that this comes from a Travis continuous integration environment that is based on Ubuntu Trusty (14.04) whose default prepackaged ICU is version 52.
> 
Yes, that makes sense.

Andi..

**Comment by ovalhub** [comment]
fixed
