### ISSUE TITLE
pip install pyicu fails on travis

### ISSUE THREAD

**Issue by WhyNotHugo** [ovalhub/pyicu#68]
One of my projects installs `pyicu` on travis to run some tests, but installing PyICU seems to fail.
I'm no familiar enough to explain _what's_ failing, but the entire output is here:

https://travis-ci.org/pimutils/todoman/jobs/328789538

**Comment by ovalhub** [comment]
> On Jan 14, 2018, at 11:17, Hugo Osvaldo Barrera <notifications@github.com> wrote:
> 
> One of my projects installs pyicu on travis to run some tests, but installing PyICU seems to fail.
> I'm no familiar enough to explain what's failing, but the entire output is here:
> 
> https://travis-ci.org/pimutils/todoman/jobs/328789538
> 

Your log says “Building PyICU 2.0.1 for ICU 52.1”.
This is likely fixed in HEAD. I intend to release PyICU 2.0.2 with this fix later today.

Andi..

**Comment by ovalhub** [comment]
PyICU 2.0.2 is now available on PyPI.
