### ISSUE TITLE
TimeUnitFormat InvalidArgsError

### ISSUE THREAD

**Issue by sharifzadesina** [ovalhub/pyicu#73]
Hi
I am using TimeUnitFormat class as mentioned [here](http://icu-project.org/apiref/icu4c/classicu_1_1TimeUnitFormat.html).
But I am getting `icu.InvalidArgsError` always.
```python
formatter = TimeUnitFormat(Locale('en_US'))
obj = TimeUnitAmount(1, 0) # 0 means YEAR
print(formatter.format(obj))
```

**Comment by ovalhub** [comment]
On Sat, 20 Jan 2018, Sina wrote:

> Hi
> I am using TimeUnitFormat class as mentioned in [here](http://icu-project.org/apiref/icu4c/classicu_1_1TimeUnitFormat.html).
> But I am getting `icu.InvalidArgsError` always.
> ```python
> formatter = TimeUnitFormat(Locale('en_US'))
> obj = TimeUnitAmount(1, 0) # 0 means YEAR
> print(return formatter.format(obj))
> ```

The issue is that a TimeUnitAmount is a Measure, not a Formattable.
To format a Measure with TimeUnitFormat, you need to use its formatMeasure 
method or its formatMeasurePerUnit() companion, which are both missing in 
PyICU currently.

I now added wrappers for them in HEAD:

     >>> from icu import *
     >>> formatter = TimeUnitFormat(Locale('en_US'))
     >>> obj = TimeUnitAmount(1, UTimeUnitFields.YEAR)
     >>> formatter.formatMeasure(obj)
     u'1 year

The actual ICU method is called formatMeasures() and it takes an array of
Measure objects. Because the Measure() constructor is protected, it's
difficult to create an array of Measure objects from the python Measure object
wrappers that a formatMeasures wrapper would receive.
formatMeasure() is just a one Measure version of the same function.

The formatMeasurePerUnit() method is also available now:

     >>> formatter.formatMeasurePerUnit(obj, MeasureUnit.createMeter())
     u'1 year per meter'

Andi..

**Comment by sharifzadesina** [comment]
Thank you for the update.
It seems `formatMeasure` is not part of ICU, so I think we should not have it also here, instead of that why you don't make `Measure` constructor public like ICU?

**Comment by ovalhub** [comment]
> On Jan 21, 2018, at 12:43, Sina <notifications@github.com> wrote:
> 
> Thank you for the update.
> It seems formatMeasure is not part of ICU, so I think we should not have it also here, instead of that why you don't make Measure constructor public like ICU?
> 
It’s the ICU constructor that is not public, not something under PyICU’s control.
As for formatMeasure(), I could rename it to formatMeasures() and make it fail when more than one Mesure is passed in ?

Andi..

**Comment by sharifzadesina** [comment]
Are you sure it is not public? I didn't check the source but in the API doc it is public. see [here](http://icu-project.org/apiref/icu4c/classicu_1_1Measure.html).

> As for formatMeasure(), I could rename it to formatMeasures() and make it fail when more than one Mesure is passed in ?

Yes it would be so much better to make API exactly same as ICU API, we can just throw error if people put more that one Mesure.

**Comment by ovalhub** [comment]
> On Jan 21, 2018, at 13:33, Sina <notifications@github.com> wrote:
> 
> Are you sure it is not public? I didn't check the source but in the API doc it is public. see here.
> 
The default constructor is listed under protected functions (scroll down a bit). This is what gets called when you do:
  Measure *measures = new Measure[len];
> As for formatMeasure(), I could rename it to formatMeasures() and make it fail when more than one Mesure is passed in ?
> 
> Yes it would be so much better to make API exactly same as ICU API, we can just throw error if people put more that one Mesure.
> 
No, the python API is not identical to the C++ version intentionally. Making it a more pythonic makes PyICU that more enjoyable and easy to use.
I can add both, formatMeasures(sequence of one Measure) and formatMeasure(Measure)
(both with optional FieldPosition arg).

Andi..

**Comment by sharifzadesina** [comment]
> The default constructor is listed under protected functions (scroll down a bit). This is what gets called when you do:
>  Measure *measures = new Measure[len];

True, but the constructor with extra argument is not protected, so why we can't use it?

> I can add both, formatMeasures(sequence of one Measure) and formatMeasure(Measure)
> (both with optional FieldPosition arg).

Yes, they are not EXACTLY same, but we have same method names and same class names, so I think it is better to use `formatMeasures` method and accept and array of Measures but throw error when people have more that one Measure in the array, this way we can fix this later without BC break.

**Comment by ovalhub** [comment]
On Sun, 21 Jan 2018, Sina wrote:

>> The default constructor is listed under protected functions (scroll down a bit). This is what gets called when you do:
>>  Measure *measures = new Measure[len];
>
> True, but the constructor with extra argument is not protected, so why we 
> can't use it?

Because C++ says that new Measure[len] calls Measure() to initialize the 
array of Measure objects being allocated.
If you have something else in mind, please propose a patch.

>> I can add both, formatMeasures(sequence of one Measure) and formatMeasure(Measure)
>> (both with optional FieldPosition arg).
>
> Yes, they are not EXACTLY same, but we have same method names and same 
> class names, so I think it is better to use `formatMeasures` method and 
> accept and array of Measures but throw error when people have more that 
> one Measure in the array, this way we can fix this later without BC break.

I now added formatMeasures() support for one Measure:

     >>> from icu import *
     >>> formatter = TimeUnitFormat(Locale('en_US'))
     >>> obj = TimeUnitAmount(1, UTimeUnitFields.YEAR)
     >>> formatter.formatMeasures((obj,))
     u'1 year

Andi..

**Comment by sharifzadesina** [comment]
Thank you.
I think, if you prefer, you can remove `formatMeasure` method, so there won't be any confusing.
Also as we can create `TimeUnitAmount` and `CurrencyAmount` classes, so we can accept an array without more than 1 item, for example like this:
```python
from icu import *
obj1 = TimeUnitAmount(1, UTimeUnitFields.YEAR)
ob2 = TimeUnitAmount(2, UTimeUnitFields.MONTH)
formatter.formatMeasures((obj1, ob2,)) # 1 year, 2 months
```
