### ISSUE TITLE
Error on importing PyICU in a conda environment Ubuntu 17.10

### ISSUE THREAD

**Issue by pankaja92** [ovalhub/pyicu#74]
My python version is python 3.6 and I installed PyICU in a conda environment (As I'm already using Tensofrlow and NLTK in the environment) . 

And use `import icu` it doesn't give me any syntax error (on Pycharm) , but when I execute the code it gives me this error.
```

Traceback (most recent call last):
  File "/home/pankaja/PycharmProjects/teamspark/testing/sinhalasort.py", line 1, in <module>
    import icu
  File "/home/pankaja/anaconda3/envs/tensorflow/lib/python3.5/site-packages/icu/__init__.py", line 37, in <module>
    from _icu import *
ImportError: libicui18n.so.58: cannot open shared object file: No such file or directory
```

I can install and use pyicu in the normal environment. But I need to use this in this conda environment. So how can I do that ?

**Comment by ovalhub** [comment]
On Sun, 21 Jan 2018, Thidasa Pankaja Paranavitharana wrote:

> My python version is python 3.6 and I installed PyICU in a conda environment (As I'm already using Tensofrlow and NLTK in the environment) .
>
> And use `import icu` it doesn't give me any syntax error (on Pycharm) , but when I execute the code it gives me this error.
> ```
>
> Traceback (most recent call last):
>  File "/home/pankaja/PycharmProjects/teamspark/testing/sinhalasort.py", line 1, in <module>
>    import icu
>  File "/home/pankaja/anaconda3/envs/tensorflow/lib/python3.5/site-packages/icu/__init__.py", line 37, in <module>
>    from _icu import *
> ImportError: libicui18n.so.58: cannot open shared object file: No such file or directory
> ```
>
> I can install and use pyicu in the normal environment. But I need to use 
> this in this conda environment. So how can I do that ?

The error means that the ICU shared library is not found by the shared 
library linker to load with the _icu (PyICU) python extension.
Either you didn't install ICU in your environment at all or it can't be 
found in the places that the shared library linker expects it to.
If you know where libicui18n.so.58 actually is, you can try to add its 
directory to LD_LIBRARY_PATH (although I don't know what kind of environment 
'conda' is so I don't know if this makes any sense there).

Andi..
