### ISSUE TITLE
Pip install fails with gcc error on Ubuntu 16.04.1 LTS, ICU 58.2

### ISSUE THREAD

**Issue by gianlucascoccia** [ovalhub/pyicu#76]
I can't manage to get it working on Ubuntu 16.04.1 LTS, ICU 58.2, Anaconda python 3.6.

> Collecting pyicu
>   Downloading PyICU-2.0.2.tar.gz (194kB)
>     100% |████████████████████████████████| 194kB 403kB/s 
> Building wheels for collected packages: pyicu
>   Running setup.py bdist_wheel for pyicu ... error
>   Complete output from command /home/gian/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ticen7jn/pyicu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpqyyqrreupip-wheel- --python-tag cp36:
>   
>   Building PyICU 2.0.2 for ICU 58.2
>   
>   Adding CXXFLAGS="-I/home/gian/anaconda3/include" from /home/gian/anaconda3/bin/icu-config
>   Adding LDFLAGS="-L/home/gian/anaconda3/lib -licui18n -licuuc -licudata" from /home/gian/anaconda3/bin/icu-config
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build/lib.linux-i686-3.6
>   copying PyICU.py -> build/lib.linux-i686-3.6
>   creating build/lib.linux-i686-3.6/icu
>   copying icu/__init__.py -> build/lib.linux-i686-3.6/icu
>   running build_ext
>   building '_icu' extension
>   creating build/temp.linux-i686-3.6
>   gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c _icu.cpp -o build/temp.linux-i686-3.6/_icu.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>   cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>   gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c bases.cpp -o build/temp.linux-i686-3.6/bases.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>   cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>   gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c calendar.cpp -o build/temp.linux-i686-3.6/calendar.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>   cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>   gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c char.cpp -o build/temp.linux-i686-3.6/char.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>   cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>   gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c charset.cpp -o build/temp.linux-i686-3.6/charset.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>   cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>   gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c collator.cpp -o build/temp.linux-i686-3.6/collator.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>   cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>   gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c common.cpp -o build/temp.linux-i686-3.6/common.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>   cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>   gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c dateformat.cpp -o build/temp.linux-i686-3.6/dateformat.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>   cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>   gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c errors.cpp -o build/temp.linux-i686-3.6/errors.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>   cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>   gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c format.cpp -o build/temp.linux-i686-3.6/format.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>   cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>   gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c idna.cpp -o build/temp.linux-i686-3.6/idna.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>   cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>   gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c iterators.cpp -o build/temp.linux-i686-3.6/iterators.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>   cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>   gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c layoutengine.cpp -o build/temp.linux-i686-3.6/layoutengine.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>   cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>   gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c locale.cpp -o build/temp.linux-i686-3.6/locale.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>   cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>   gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c measureunit.cpp -o build/temp.linux-i686-3.6/measureunit.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>   cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>   measureunit.cpp:538:9: warning: identifier ‘nullptr’ is a keyword in C++11 [-Wc++0x-compat]
>            int32_t size = MeasureUnit::getAvailable(type_name, nullptr, 0, status);
>            ^
>   measureunit.cpp: In function ‘PyObject* t_measureunit_getAvailable(PyTypeObject*, PyObject*)’:
>   measureunit.cpp:538:61: error: ‘nullptr’ was not declared in this scope
>            int32_t size = MeasureUnit::getAvailable(type_name, nullptr, 0, status);
>                                                                ^
>   error: command 'gcc' failed with exit status 1
>   
>   ----------------------------------------
>   Failed building wheel for pyicu
>   Running setup.py clean for pyicu
> Failed to build pyicu
> Installing collected packages: pyicu
>   Running setup.py install for pyicu ... error
>     Complete output from command /home/gian/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ticen7jn/pyicu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-zcwnimo6-record/install-record.txt --single-version-externally-managed --compile:
>     
>     Building PyICU 2.0.2 for ICU 58.2
>     
>     Adding CXXFLAGS="-I/home/gian/anaconda3/include" from /home/gian/anaconda3/bin/icu-config
>     Adding LDFLAGS="-L/home/gian/anaconda3/lib -licui18n -licuuc -licudata" from /home/gian/anaconda3/bin/icu-config
>     running install
>     running build
>     running build_py
>     creating build
>     creating build/lib.linux-i686-3.6
>     copying PyICU.py -> build/lib.linux-i686-3.6
>     creating build/lib.linux-i686-3.6/icu
>     copying icu/__init__.py -> build/lib.linux-i686-3.6/icu
>     running build_ext
>     building '_icu' extension
>     creating build/temp.linux-i686-3.6
>     gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c _icu.cpp -o build/temp.linux-i686-3.6/_icu.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>     cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>     gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c bases.cpp -o build/temp.linux-i686-3.6/bases.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>     cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>     gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c calendar.cpp -o build/temp.linux-i686-3.6/calendar.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>     cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>     gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c char.cpp -o build/temp.linux-i686-3.6/char.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>     cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>     gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c charset.cpp -o build/temp.linux-i686-3.6/charset.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>     cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>     gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c collator.cpp -o build/temp.linux-i686-3.6/collator.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>     cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>     gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c common.cpp -o build/temp.linux-i686-3.6/common.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>     cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>     gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c dateformat.cpp -o build/temp.linux-i686-3.6/dateformat.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>     cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>     gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c errors.cpp -o build/temp.linux-i686-3.6/errors.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>     cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>     gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c format.cpp -o build/temp.linux-i686-3.6/format.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>     cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>     gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c idna.cpp -o build/temp.linux-i686-3.6/idna.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>     cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>     gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c iterators.cpp -o build/temp.linux-i686-3.6/iterators.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>     cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>     gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c layoutengine.cpp -o build/temp.linux-i686-3.6/layoutengine.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>     cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>     gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c locale.cpp -o build/temp.linux-i686-3.6/locale.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>     cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>     gcc -pthread -B /home/gian/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gian/anaconda3/include/python3.6m -c measureunit.cpp -o build/temp.linux-i686-3.6/measureunit.o -DPYICU_VER="2.0.2" -I/home/gian/anaconda3/include
>     cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>     measureunit.cpp:538:9: warning: identifier ‘nullptr’ is a keyword in C++11 [-Wc++0x-compat]
>              int32_t size = MeasureUnit::getAvailable(type_name, nullptr, 0, status);
>              ^
>     measureunit.cpp: In function ‘PyObject* t_measureunit_getAvailable(PyTypeObject*, PyObject*)’:
>     measureunit.cpp:538:61: error: ‘nullptr’ was not declared in this scope
>              int32_t size = MeasureUnit::getAvailable(type_name, nullptr, 0, status);
>                                                                  ^
>     error: command 'gcc' failed with exit status 1
>     
>     ----------------------------------------
> Command "/home/gian/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ticen7jn/pyicu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-zcwnimo6-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ticen7jn/pyicu/
>

**Comment by ovalhub** [comment]
You don’t have -std=c++11 set in your compiler flags. This should not be required until ICU 60.
My bad for using ‘nullptr’ instead of NULL. I should have a fix in HEAD shortly.

Andi..

**Comment by ovalhub** [comment]
Please, try again by refreshing ICU from HEAD revision at github, and let
me know if this solves the problem.

Thanks !

Andi..

**Comment by gianlucascoccia** [comment]
>  try again by refreshing ICU from HEAD revision at github

Not sure I understood you correctly, but this is what I did:

`pip install git+https://github.com/ovalhub/pyicu`

and it worked! Thank you!

**Comment by ovalhub** [comment]
On Sun, 28 Jan 2018, gianlucascoccia wrote:

>>  try again by refreshing ICU from HEAD revision at github
>
> Not sure I understood you correctly, but this is what I did:
>
> `pip install git+https://github.com/ovalhub/pyicu`
>
> and it worked! Thank you!

That's what I meant. I didn't know about this 'pip' trick, good to know.
Thank you for verifying the fix !

Andi..
