### ISSUE TITLE
undefined symbol: _ZTIN6icu_6014TransliteratorE

### ISSUE THREAD

**Issue by maveryKearney** [ovalhub/pyicu#77]
With linux mint/ python 3.6.4/ icu 60.2/ pyicu 20.3.

1. - Having successfully compiled and tested icu 60.2
2. - Having built and installed pyicu successfully
3. - And invoked the version of python that has pyicu. so that I am at the python prompt.

When I type:
`>>> import icu

`I get:
**ImportError: ...<path to python exe>... /lib/python3.6/site-packages/PyICU-2.0.3-py3.6-linux-x86_64.egg/_icu.cpython-36dm-x86_64-linux-gnu.so: undefined symbol: _ZTIN6icu_6014TransliteratorE**

I have been after this problem for several days, I have looked through the code for that symbol. I have encountered similar problems in bits of icu I don't use, and worked around them by commenting out the reference. I haven't found a reference to this symbol. 

I am not using the transliterators so eliminating them entirely from pyicu would work also. I'll perhaps explore that next.

I have a suspicion it might be a compilation problem associated with the processor on this machine and whatever compiler magic the icuConfiguration tool comes up with.  

Things work well enough for now with python 3.6.4/ icu 59.1/ pyicu 1.97, But I'll have to face this at some point. 

Anyone have any insights or suggestions?

-m

**Comment by ovalhub** [comment]
On Mon, 12 Feb 2018, maveryKearney wrote:

> With linux mint/ python 3.6.4/ icu 60.2/ pyicu 20.3.
>
> 1. - Having successfully compiled and tested icu 60.2
> 2. - Having built and installed pyicu successfully
> 3. - And invoked the version of python that has pyicu. so that I am at the python prompt.
>
> When I type:
> `>>> import icu
>
> `I get:
> **ImportError: ...<path to python exe>... /lib/python3.6/site-packages/PyICU-2.0.3-py3.6-linux-x86_64.egg/_icu.cpython-36dm-x86_64-linux-gnu.so: undefined symbol: _ZTIN6icu_6014TransliteratorE**
>
> I have been after this problem for several days, I have looked through the code for that symbol. I have encountered similar problems in bits of icu I don't use, and worked around them by commenting out the reference. I haven't found a reference to this symbol.
>
> I am not using the transliterators so eliminating them entirely from pyicu would work also. I'll perhaps explore that next.
>
> I have a suspicion it might be a compilation problem associated with the processor on this machine and whatever compiler magic the icuConfiguration tool comes up with.
>
> Things work well enough for now with python 3.6.4/ icu 59.1/ pyicu 1.97, But I'll have to face this at some point.
>
> Anyone have any insights or suggestions?

This error means that the version of the ICU shared library you are picking 
up at runtime (that the shared library loader is picking up) is not the one
that PyICU was built and linked against.

On MacOSX, you can use the otool program on the pyicu python extension to 
list which version of ICU it was built with. On linux, I believe, there is 
something called 'ldd' that does this as well.

You very likely have multiple versions of ICU installed (or multiple 
versions of the icu-dev package, or header files, or ICU libraries 
installed). Get rid of all of them but the one you actually want to use.
Then build PyICU again.

Andi..

**Comment by maveryKearney** [comment]
I suspect the icu-dev package, which I managed to never have to contend with until this upgrade.

It wasn’t on the machine OS at all initially and I installed the “latest”, which may not have actually

been the latest. Such is package management.

 

I’ll see what I find and report back.

-m

**Comment by maveryKearney** [comment]
Andi,
       There was a 55.1 version of icu-devtools on the system. I believe I installed it in the process of my investigation. It may have a enabled the icu59.1 integration. I can't tell you if that particular combination actually work under stress. It did pass a liveness test. 
      Regardless, I wanted a valid integration. 

      I downloaded icu-devtools for my platform 64bit amd. from
 https://ubuntu.pkgs.org/18.04/ubuntu-main amd64/icu-devtools_60.2-3ubuntu1_amd64.deb.html

Superficially it looks like a standard icu source directory, but I didn't do an exhaustive inspection of the files for differences. Following the standard config/build/install process, this set of files works for me. I no longer see the undefined symbol error that I reported.

A minor further issue easily resolved was that the pyicu setup.py calls icu-config, and I did not have the icu bin area in my path. I added the area to my path, and voila. 

All set for now

**Comment by maveryKearney** [comment]
Thanks
-m

**Comment by ovalhub** [comment]
> On Feb 13, 2018, at 16:50, maveryKearney <notifications@github.com> wrote:
> 
> Thanks
> 
You’re welcome. I’m glad it was easy to resolve.

Andi..
