### ISSUE TITLE
Hamaz (U+0621) is wrongly considered a diacritic in Arabic

### ISSUE THREAD

**Issue by mzeidhassan** [ovalhub/pyicu#78]
Hi all,

I am trying to normalize some Arabic text. I use the following code and it works just fine and removes all diacritics, but it also removes the Arabic character 'Hamaz' (U+0621) which shouldn't be considered a diacritic. 
Is there a way to skip removing hamza from Arabic text. 

Here is my function that I am using:
`from icu import UnicodeString, Transliterator, UTransDirection
def normalize_string(s):
    u = UnicodeString(s)
    t = Transliterator.createInstance("NFD; [:M:] Remove; NFC", UTransDirection.FORWARD)
    t.transliterate(u)
    normalized = str(u)
    return normalized
normalize_string('صِراطَ الَّذينَ أَنعَمتَ عَلَيهِم غَيرِ المَغضوبِ عَلَيهِم وَلَا الضّالّينَ')`

The output is:

> 'صراط الذين انعمت عليهم غير المغضوب عليهم ولا الضالين'

Thanks,
Mohamed Zeid

**Comment by ovalhub** [comment]
> On Feb 24, 2018, at 16:09, Mohamed Zeid <notifications@github.com> wrote:
> 
> Hi all,
> 
> I am trying to normalize some Arabic text. I use the following code and it works just fine and removes all diacritics, but it also removes the Arabic character 'Hamaz' (U+0621) which shouldn't be considered a diacritic.
> Is there a way to skip removing hamza from Arabic text.
> 
PyICU is only a wrapper around C/C++ ICU. Please, ask ICU usage questions on the ICU user list:
http://site.icu-project.org/contacts

Thanks !

Andi..

**Comment by mzeidhassan** [comment]
Thanks Andi. I will contact them and see. 
I also found out that it remove hamza only when it's combined with the 'alef' character only; i.e. from alef with hamza above and hamza below.

I am closing this for now. Thanks again for your prompt support! 
Kind regards,
Mohamed
