### ISSUE TITLE
Option to bundle ICU with the extension?

### ISSUE THREAD

**Issue by madig** [ovalhub/pyicu#79]
Hi,
I'd like to know your stance on (optionally) bundling ICU for distribution via PyPI. The goal is to make it possible for users to just `pip install pyicu` and be ready to go on the major platforms Windows, Linux and macOS. This would probably imply setting the pyicu version number to match ICU's. The main problem will probably be the 30 MB you'd have to put in a wheel, the second problem the build system used by ICU... so. Opinions? Better ideas?

**Comment by madig** [comment]
I just compiled pyicu with a static x64 ICU lib linked in and _icu.so weighted in at 35 MB. 😞

**Comment by ovalhub** [comment]
On Tue, 13 Mar 2018, Nikolaus Waxweiler wrote:

> Hi, I'd like to know your stance on (optionally) bundling ICU for 
> distribution via PyPI. The goal is to make it possible for users to just 
> `pip install pyicu` and be ready to go on the major platforms Windows, 
> Linux and macOS. This would probably imply setting the pyicu version 
> number to match ICU's. The main problem will probably be the 30 MB you'd 
> have to put in a wheel, the second problem the build system used by ICU... 
> so. Opinions? Better ideas?

I'm very much against shipping any binaries.

ICU is included in all Linux distributions and Mac OS.
PyICU is included in some Linux distributions as well.

I have no access to Windows so I can't speak much about it.

Andi..

**Comment by ovalhub** [comment]
On Tue, 13 Mar 2018, Nikolaus Waxweiler wrote:

> I just compiled pyicu with a static x64 ICU lib linked in and _icu.so 
> weighted in at 35 MB. ?

Is that a question ?

Andi..

**Comment by madig** [comment]
Fair enough. The main advantage (for us) is version pinning across a heterogeneous computing environment. Linux distributions usually don't support installing a very specific version and packaging is a pain, homebrew on macOS doesn't seem to support it conveniently, either. We will look at going about this differently.

> Is that a question ?

No, a finding :)

**Comment by ovalhub** [comment]
> On Mar 14, 2018, at 03:39, Nikolaus Waxweiler <notifications@github.com> wrote:
> 
> Fair enough. The main advantage (for us) is version pinning across a heterogeneous computing environment. Linux distributions usually don't support installing a very specific version and packaging is a pain, homebrew on macOS doesn't seem to support it conveniently, either. We will look at going about this differently.
> 
That's the tradeoff with any of these distributions - you depend on the version they ship. If you want your own pinned version, you need to do your own build. Why would a binary wheel from pypi not suffer from the same version problem ?
> Is that a question ?
> 
> No, a finding :)
> 
The size makes sense. There is a lot of resource data in ICU and the api is pretty large.

Andi..

**Comment by madig** [comment]
> That's the tradeoff with any of these distributions - you depend on the version they ship. If you want your own pinned version, you need to do your own build. Why would a binary wheel from pypi not suffer from the same version problem ?

Because PyPI keeps old versions around and you simply pin pyicu==something in your requirements.txt. :)

**Comment by ovalhub** [comment]
> On Mar 14, 2018, at 08:39, Nikolaus Waxweiler <notifications@github.com> wrote:
> 
> That's the tradeoff with any of these distributions - you depend on the version they ship. If you want your own pinned version, you need to do your own build. Why would a binary wheel from pypi not suffer from the same version problem ?
> 
> Because PyPI keeps old versions around and you simply pin pyicu==something in your requirements.txt. :)
> 
Linux package systems don't offer old versions ?
It seems that the problem there might be the opposite, actually - they're late in getting new versions or never get them, even, in the LTS versions.
There are many PyICU users running on rather old ICU versions because "they're on some LTS version" stuck in 2014.

**Comment by madig** [comment]
> Linux package systems don't offer old versions?

Usually only specific, distribution-dependent versions, if at all. The main problem is that most distribution package systems don't offer what we want, when we want.

> There are many PyICU users running on rather old ICU versions because "they're on some LTS version" stuck in 2014.

Exactly -- and (optionally) bundling ICU with the Python package side-steps the issue completely in a cross-platform way :) The size is a bit prohibitive though, which is why I can understand hesitance.

**Comment by ovalhub** [comment]
> On Mar 14, 2018, at 08:58, Nikolaus Waxweiler <notifications@github.com> wrote:
> 
> Linux package systems don't offer old versions?
> 
> Usually only specific, distribution-dependent versions, if at all. The main problem is that most distribution package systems don't offer what we want, when we want.
> 
> There are many PyICU users running on rather old ICU versions because "they're on some LTS version" stuck in 2014.
> 
> Exactly -- and (optionally) bundling ICU with the Python package side-steps the issue completely in a cross-platform way :) The size is a bit prohibitive though, which is why I can understand hesitance.
> 
Size is an issue for sure, especially multiplied by at least 6 considering the variants (python2, python3) x (macos, linux, windows) but I'm against shipping binaries in any case (in no particular order):
  - You're shutting out smaller platforms like the BSDs (not in three OSs above)
  - You have to also match compilers with the compilers used to build the python you're running: clang, gcc, msvc, ... especially with c++ so that multiplier is larger than 6 or some people on those 3 OSs are also shut out.
  - You have to take responsibility for your binaries: what if there are viruses in them ? 
I have no access to Windows, I'd have to trust your Windows binaries since you'd offer to build those, right ?
 - repeat that for each version: you want old version support, what if there is a bug in the build of that version ? does it get fixed ? for how long ?
 - And so on...

**Comment by madig** [comment]
>  You're shutting out smaller platforms like the BSDs (not in three OSs above)

Not really, they just get the normal sdist and have to compile something on their own as usual.

> You have to take responsibility for your binaries: what if there are viruses in them ? I have no access to Windows, I'd have to trust your Windows binaries since you'd offer to build those, right ?

Well yes, but they'd be build by a CI service under your control, not me. Have a look at https://github.com/matthew-brett/multibuild and https://github.com/fonttools/ttfautohint-py as an implementation.

> repeat that for each version: you want old version support, what if there is a bug in the build of that version ? does it get fixed ? for how long ?

When bundling a library, each new upstream version requires an explicit update on your side. Since you're only bundling one version, there is no old upstream version to support. A bug in upstream requires a new upstream version; a bug on your side gets a fix from your side, the upstream version stays the same :)

**Comment by ovalhub** [comment]
> On Mar 14, 2018, at 09:59, Nikolaus Waxweiler <notifications@github.com> wrote:
> 
> You're shutting out smaller platforms like the BSDs (not in three OSs above)
> 
> Not really, they just get the normal sdist and have to compile something on their own as usual.
> 
Ah, ok, so your saying "cross-platform" just means "as long as it includes yours" :-)
> You have to take responsibility for your binaries: what if there are viruses in them ? I have no access to Windows, I'd have to trust your Windows binaries since you'd offer to build those, right ?
> 
> Well yes, but they'd be build by a CI service under your control,
> 
No, not under my control but under the control of whoever runs the CI service.
> not me. Have a look at https://github.com/matthew-brett/multibuild and https://github.com/fonttools/ttfautohint-py as an implementation.
> 
> repeat that for each version: you want old version support, what if there is a bug in the build of that version ? does it get fixed ? for how long ?
> 
> When bundling a library, each new upstream version requires an explicit update on your side. Since you're only bundling one version, there is no old upstream version to support.
> 
I don't follow. You wanted to use version pinning. How long do you expect the binary build version you pinned to to be supported ?
> A bug in upstream requires a new upstream version; a bug on your side gets a fix from your side, the upstream version stays the same :)
> 
Well, stepping back a bit, you can see I'm not sympathetic to the idea of shipping binaries. This being open source, you are more than welcome to provide your own fork of PyICU+ICU with binaries on PyPI or elsewhere (see below). It's a burden I'm not willing to take on, nor its responsibility.

I've had users do this in the past, however, especially for Windows builds for my JCC project. In fact, a quick Google search for "jcc binary builds" yields this top result: https://www.lfd.uci.edu/~gohlke/pythonlibs/
It has Windows binaries for both PyICU and JCC, python2 and 3, 32- and 64-bit, and for countless other PyPI projects. Maybe what you want actually exists already ?

Andi..

**Comment by bgermann** [comment]
There is https://pypi.org/project/PyICU-binary
@Zombie-Feynman Would you be willing to publish Windows and MacOS wheels as well?

**Comment by ovalhub** [comment]
> On Nov 11, 2018, at 03:26, Zombie-Feynman <notifications@github.com> wrote:
> 
> There is https://pypi.org/project/PyICU-binary
> @Zombie-Feynman Would you be willing to publish Windows and MacOS wheels as well?
> 

No, sorry, there are just too many possible binary configurations.

**Comment by bgermann** [comment]
@wtolson Would you be willing to publish Windows and macOS wheels for PyICU-binary in addition to manylinux1 ones?

**Comment by loretoparisi** [comment]
@madig did you compile for macOS? I cannot find any way to import the library after installed via `pip`, have a look at https://github.com/ovalhub/pyicu/issues/101#issuecomment-487954584

**Comment by wtolson** [comment]
@bgermann I compiled and published macosx wheels for pyicu-binary and I've published the scripts I'm using to build them here: https://github.com/wtolson/pyicu-binary

I don't have access to a windows machine at the time so that's going to have to be a contribution from someone else.

**Comment by bgermann** [comment]
Thanks for coming back to me.
