### ISSUE TITLE
compiling fails on pypy3

### ISSUE THREAD

**Issue by jinty** [ovalhub/pyicu#80]
When installing with pypy3 I get:

```
    common.cpp:213:28: error: use of undeclared identifier 'PyUnicode_New'
            PyObject *result = PyUnicode_New(len32, max_char);
```

I got the same result on OSX as well as Debian stretch.

**Comment by ovalhub** [comment]
It looks like pypy3 still uses the old-style unicode python3 unicode implementation.
I fixed the build error but importing the resulting 'icu' module segfaults...

**Comment by ovalhub** [comment]
I fixed the crasher now. It seems that having a tp_doc field set to "" causes PyType_Ready() to crash
in pypy3. Setting the tp_doc to a non empty string in the two types defined in tzinfo.cpp fixed the problem.
The tests pass - it looks like pypy3 6.0 and pyicu (HEAD) are working fine together now.
