### ISSUE TITLE
OSX C++ 11 Build Error

### ISSUE THREAD

**Issue by hexxonxonx** [ovalhub/pyicu#84]
In order to build PyICU on OSX I had to pass flags to gcc:

export CFLAGS=-std=c++11

Would it be possible to pass these in the script so others don't have the error, or add to docs?

**Comment by ovalhub** [comment]
On Mon, 9 Jul 2018, hexxonxonx wrote:

> In order to build PyICU on OSX I had to pass flags to gcc:
>
> export CFLAGS=-std=c++11
>
> Would it be possible to pass these in the script so others don't have the 
> error, or add to docs?

If you have icu-config installed and the build can find it on your path, 
it'll make use of it and that flag is added for you. If you don't use 
icu-config, you are responsible for the flags and they depend on the version 
of ICU you're building with.
Whether icu-config is found and/or used is shown on stdout during the 
build, including the full path of the icu-config used.

Andi..

**Comment by hexxonxonx** [comment]
Fair enough this was via using pip to install PyICU so I brought it up here.

**Comment by ovalhub** [comment]
> On Jul 9, 2018, at 19:58, hexxonxonx <notifications@github.com> wrote:
> 
> Fair enough this was via using pip to install PyICU so I brought it up here.
> 
The icu-config program is part of ICU, not PyICU, and pip is irrelevant here. It all depends on how you installed ICU first. Pip doesn't do this for you.

Andi..

**Comment by ovalhub** [comment]
> On Jul 10, 2018, at 01:24, hexxonxonx <notifications@github.com> wrote:
> 
> When pip invokes "setup.py bdist_wheel" their is a compiler error on OSX using the clang compiler as it is not setup to use the CPP 11 syntax. Clang is the compiler that comes with the development tools from Apple.
> 
> So while compiling the C++ files in the root of the setup directory it errors, is that part of ICU or would that be part of your package?
> 
The reason the compile fails is because of the
missing c++11 flag, as you reported.
The reason the flag is missing is because you don't have the icu-config program installed. It is what tells setup.py what to put into the c++ compiler flags (and others). You installed ICU (I suppose), not pip.
If you don't have icu-config installed, you are responsible for setting the flags in setup.py (this is valid for osx and linux only, on other platforms you are always responsible for setting the flags in setup.py but there are some sensible defaults preset).

**Comment by hexxonxonx** [comment]
It was installed via homebrew which would explain it.

**Comment by ovalhub** [comment]
> On Jul 10, 2018, at 01:33, hexxonxonx <notifications@github.com> wrote:
> 
> It was installed via homebrew which would explain it.
> 
It is a bug of homebrew not to install icu-config.

**Comment by hexxonxonx** [comment]
I'll go look at the recipe on their end, thanks.
