### ISSUE TITLE
ListFormatter tests fail

### ISSUE THREAD

**Issue by jnak** [ovalhub/pyicu#9]
It seems that from icu import \* does not import ListFormatter.

```
EE
======================================================================
ERROR: testDefault (__main__.TestListFormatter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_ListFormatter.py", line 34, in testDefault
    formatter = ListFormatter.createInstance()
NameError: global name 'ListFormatter' is not defined

======================================================================
ERROR: testLocale (__main__.TestListFormatter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_ListFormatter.py", line 41, in testLocale
    formatter = ListFormatter.createInstance(Locale.getFrance())
NameError: global name 'ListFormatter' is not defined

----------------------------------------------------------------------
Ran 2 tests in 0.000s
```

Does it work for you?

**Comment by ovalhub** [comment]
On Wed, 28 Oct 2015, Julien Nakache wrote:

> It seems that from icu import * does not import ListFormatter.
>
> ```
> EE
> ======================================================================
> ERROR: testDefault (__main__.TestListFormatter)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>  File "test_ListFormatter.py", line 34, in testDefault
>    formatter = ListFormatter.createInstance()
> NameError: global name 'ListFormatter' is not defined
>
> ======================================================================
> ERROR: testLocale (__main__.TestListFormatter)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>  File "test_ListFormatter.py", line 41, in testLocale
>    formatter = ListFormatter.createInstance(Locale.getFrance())
> NameError: global name 'ListFormatter' is not defined
>
> ----------------------------------------------------------------------
> Ran 2 tests in 0.000s
> ```
>
> Does it work for you?

Yes:

>>> from icu import *
>>> ListFormatter
<type 'icu.ListFormatter'>

$ python trunk/test/test_ListFormatter.py
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK

Andi..
