### ISSUE TITLE
Please use pkg-config to detect icu

### ISSUE THREAD

**Issue by hughmcmaster** [ovalhub/pyicu#92]
`icu-config` has been deprecated by its upstream developers for some years now. In icu 63.1, `icu-config` is optional to install, but installed by default. In the next version, `icu-config` will no longer be installed by default.

The developers recommend downstream packages use `pkg-config` to detect the icu libraries.

Please let me know if you need any help with this change.

**Comment by ovalhub** [comment]
I've never used pkg-config before. What is an example command line to detect the icu libs and headers using pkg-config ?
Thanks !

**Comment by hughmcmaster** [comment]
If you are familiar with `autoconf`, read https://autotools.io/pkgconfig/pkg_check_modules.html for a good overview of `pkg-config`.

To use `pkg-config` with Python, I highly recommend https://github.com/matze/pkgconfig, as its syntax is basically the same as the `autoconf` macro. This webpage also has some nice examples of calls. (This module is available from https://pypi.org/project/pkgconfig/).

To get started, use `pkgconfig.exists('icu-i18n')`, `pkgconfig.cflags('icu-i18n')` and `pkgconfig.libs('icu-i18n')`.

You could also use `icu-uc` if internationalization is not important (see http://userguide.icu-project.org/howtouseicu).

**Comment by ovalhub** [comment]
On Wed, 28 Nov 2018, Hugh McMaster wrote:

> If you are familiar with `autoconf`, read 
> https://autotools.io/pkgconfig/pkg_check_modules.html for a good overview 
> of `pkg-config`.
>
> To use `pkg-config` with Python, I highly recommend 
> https://github.com/matze/pkgconfig, as its syntax is basically the same as 
> the `autoconf` macro. This webpage also has some nice examples of calls. 
> (This module is available from https://pypi.org/project/pkgconfig/).
>
> To get started, use `pkgconfig.exists('icu-i18n')`, 
> `pkgconfig.cflags('icu-i18n')` and `pkgconfig.libs('icu-i18n')`.
>
> You could also use `icu-uc` if internationalization is not important (see 
> http://userguide.icu-project.org/howtouseicu).

Thank you for all the information. It seems that pkg-config is not 
pre-installed on Mac OS (or Windows, I assume), thus this is a Linux only 
solution (albeit, a good replacement for icu-config) without any extra 
installs.

With hindsight, the use of icu-config for building PyICU has caused more 
harm than good for people for which it didn't work or for people that didn't 
have it installed. At this point, I'm *very* tempted to revert that change 
and let people edit setup.py or set the relevant env vars as documented in 
setup.py instead as has been the case in the past.

Andi..

**Comment by hughmcmaster** [comment]
No problem. pkg-config isn't pre-installed on any operating system, even Linux.

I'm happy to create a patch for you. Just let me know.

**Comment by ovalhub** [comment]
> On Dec 2, 2018, at 07:00, Hugh McMaster <notifications@github.com> wrote:
> 
> No problem. pkg-config isn't pre-installed on any operating system, even Linux.
> 
Are you thus proposing people install pkg-config before installing pyicu ?

**Comment by hughmcmaster** [comment]
Yes. Think of pkg-config as another build-dependency (like a library you might link with).

Distributions such as Debian or Ubuntu will automatically install pkg-config as a required dependency, so users don't need to worry about that. pkg-config is also easily installed on macOS and Windows. Users on those platforms will be familiar with the steps to do that.

Ultimately, though, this decision is yours.

**Comment by ovalhub** [comment]
On Mon, 3 Dec 2018, Hugh McMaster wrote:

> Yes. Think of pkg-config as another build-dependency (like a library you 
> might link with).
>
> Distributions such as Debian or Ubuntu will automatically install 
> pkg-config as a required dependency, so users don't need to worry about 
> that. pkg-config is also easily installed on macOS and Windows. Users on 
> those platforms will be familiar with the steps to do that.

That's a no-no. I'm not adding more dependencies to PyICU.
If icu-config disappears, so be it.
PyICU is already distributed by debian and similar distros.
For the others, as long as icu-config exists and is found, it's a bit easier
than editing the setup.py file or setting env vars.

> Ultimately, though, this decision is yours.

Thank you for the offer but I'm already regretting accepting the icu-config 
patch. Granted, I only see mail from people who have trouble installing, who 
have never used a C++ toolchain, not from the ones for which is just works 
(tm) but it seems to have caused more grief than ease. Replacing it with two 
dependencies (pkg-config and its python wrapper) is hardly going in the 
right direction.

Andi..

**Comment by ziima** [comment]
Hi @ovalhub: Although pyicu has packages as part of distributions, it doesn't help in cases we need to use virtualenv. Until now, it just worked, but since icu-config was removed, I don't quite see an easy way out.

**Comment by ovalhub** [comment]
> On Feb 4, 2019, at 05:16, Vlastimil Zíma <notifications@github.com> wrote:
> 
> Hi @ovalhub: Although pyicu has packages as part of distributions, it doesn't help in cases we need to use virtualenv. Until now, it just worked, but since icu-config was removed, I don't quite see an easy way out.
> 
icu-config was removed ? when ?

**Comment by ziima** [comment]
In debian it was removed lately, with libicu-dev 61-63, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=920900 that's how I got to this issue.

Currently I lack an alternative way to install pyicu to virtualenv without the icu-config.

**Comment by ovalhub** [comment]
> On Feb 4, 2019, at 23:44, Vlastimil Zíma <notifications@github.com> wrote:
> 
> In debian it was removed lately, with libicu-dev 61-63, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=920900 that's how I got to this issue.
> 
> Currently I lack an alternative way to install pyicu to virtualenv without the icu-config.
> 
Oh, I see. Indeed. Well, we're back then to the way PyICU was installed before it used icu-config:
  - edit setup.py to have the right values for CFLAGS, INCLUDES, LFLAGS that correspond to how icu is installed on your system
  - or set the corresponding env vars (see setup.py) instead of editing setup.py
Then, run:
  $ path/to/vmenv/bin/python setup.py build install

The use of icu-config was neat, when it worked, but didn't have good failure modes. PyICU is distributed in source only and needs to be compiled to match your environment, which both icu-config and python setuptools/distutils know. If icu-config is gone then we're back to manually editing setup.py.
The pkg-config solution is not portable and introduces new dependencies, making it too complicated (when compared to setting three vars)

**Comment by wfdd** [comment]
Can't pkg-config be used with an env var fallback?

**Comment by ovalhub** [comment]
> On Feb 5, 2019, at 09:45, [ɣʷufd̥] <notifications@github.com> wrote:
> 
> Can't pkg-config be used with an env var fallback?
> 
How do you use pkg-config from setup.py, without installing something else, on Linux and Mac (and Windows to be complete) ?

**Comment by ovalhub** [comment]
I now added support for falling back to trying pkg-config (Linux only) when 
icu-config is not present. This is only available at HEAD at the moment.

Please, try it out and let me know if it works for you.

And, as usual, if it doesn't work, you're not stuck. Just set PYICU_CFLAGS 
and PYICU_LFLAGS so that the compiler can find the ICU header files and 
libraries.

Thanks !

Andi..

**Comment by ziima** [comment]
Thanks for the fix. We tested it and it works both with `icu-config` and with `pkg-config` (without `icu-config`).

**Comment by ovalhub** [comment]
On Wed, 6 Feb 2019, Vlastimil Zíma wrote:

> Thanks for the fix. We tested it and it works both with `icu-config` and 
> with `pkg-config` (without `icu-config`).

Excellent !
Thank you for testing.

**Comment by ovalhub** [comment]
fixed by invoking pkg-config like is done for icu-config

**Comment by ziima** [comment]
Can we expect a new release with the fix?
