### ISSUE TITLE
collator.cpp:312:7: error: expected nested-name-specifier before ‘ImmutableInde    ’

### ISSUE THREAD

**Issue by ZmeiGorynych** [ovalhub/pyicu#93]
Ubuntu 16.04, Python 3.6 running on AWS.
I installed the icu package using `conda install icu`, it installed the version 58.2

Both when doing pip install icu and trying to build from latest source, I get the above error (full log attached). Any idea how to resolve this?

Thanks a lot,
E.
[error.txt](https://github.com/ovalhub/pyicu/files/2716493/error.txt)

**Comment by ovalhub** [comment]
> On Dec 29, 2018, at 07:20, Egor Kraev <notifications@github.com> wrote:
> 
> Ubuntu 16.04, Python 3.6 running on AWS.
> I installed the icu package using conda install icu, it installed the version 58.2
> 
> Both when doing pip install icu and trying to build from latest source, I get the above error (full log attached). Any idea how to resolve this?
> 
Hmm, not sure but could it be that the line failing the
compiler in collator.cpp:

  using ImmutableIndex = AlphabeticIndex::ImmutableIndex;

requires c++11 to be enabled ?

Either add -std=c++11 to CXXFLAGS or change that line to:

  typedef AlphabeticIndex::ImmutableIndex ImmutableIndex;

(just a wild guess)

Andi..

**Comment by ovalhub** [comment]
fixed in HEAD
