### ISSUE TITLE
Build error for PyICU 2.2 with ICU 64.1 in Windows 

### ISSUE THREAD

**Issue by ertas** [ovalhub/pyicu#98]
Hi,
I am trying to install PyICU of ver2.2 and got the following error on build:

>   measureunit.cpp(1790): error C2660: 'icu_64::number::FormattedNumber::toString': function does not take 0 arguments
>   error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

I expect toString() method to work without any arguments, so I dont know why I got such an error. Full build log up to error can be found below.

Any help is appriciated

[PyICU_v2_2 build_err.txt](https://github.com/ovalhub/pyicu/files/3029340/PyICU_v2_2.build_err.txt)

**Comment by ovalhub** [comment]
For using ICU 64.1 you need to use PyICU 2.3 which was released on Thursday to PyPI.

Andi..

**Comment by ertas** [comment]
Hi again,
When I use PyICU 2.3, I got a different error:

>  measureunit.cpp(2019): error C2121: '#': invalid character: possibly the result of a macro expansion
>     measureunit.cpp(2019): error C2679: binary '=': no operator found which takes a right-hand operand of type 'icu_64::number::FormattedNumber' (or there is no acceptable conversion)
>      measureunit.cpp(2013): error C2143: syntax error: missing ';' before 'if'
>     measureunit.cpp(2019): error C2059: syntax error: '>='
>     measureunit.cpp(2025): fatal error C1019: unexpected #else

The odd thing is, in source file measurementunit.cpp, the preprocessor condition is in line 2018, so it is odd that it shows 2019 as the error line number.

Would you reccomend that I use PyICU 2.2 with an older ICU version (60 for ex), or do you anticipate an easy fix for it?

Thanks,
Mustafa

**Comment by cgohlke** [comment]
FWIW, there are up to date binaries at https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyicu

**Comment by ovalhub** [comment]
On Mon, 1 Apr 2019, Mustafa wrote:

> Hi again,
> When I use PyICU 2.3, I got a different error:
>
>>  measureunit.cpp(2019): error C2121: '#': invalid character: possibly the result of a macro expansion
>>     measureunit.cpp(2019): error C2679: binary '=': no operator found which takes a right-hand operand of type 'icu_64::number::FormattedNumber' (or there is no acceptable conversion)
>>      measureunit.cpp(2013): error C2143: syntax error: missing ';' before 'if'
>>     measureunit.cpp(2019): error C2059: syntax error: '>='
>>     measureunit.cpp(2025): fatal error C1019: unexpected #else
>
> The odd thing is, in source file measurementunit.cpp, the preprocessor condition is in line 2018, so it is odd that it shows 2019 as the error line number.

Yeah, this is weird. I sure don't get this error. And the code looks right.
Without more details (os, compiler, python version, code snippet at location 
of error) I can't help you better.
I wonder what your version of the code looks around that error ?

> Would you reccomend that I use PyICU 2.2 with an older ICU version (60 for ex), or do you anticipate an easy fix for it?

That's up to you. It depends on what you require. If you want to use the 
latest ICU, version 64, you need to upgrade to the latest PyICU, version 
2.3.

Andi..

**Comment by ovalhub** [comment]
On Mon, 1 Apr 2019, Mustafa wrote:

> Hi,
> I am trying to install PyICU of ver2.2 and got the following error on build:
>
>>   measureunit.cpp(1790): error C2660: 'icu_64::number::FormattedNumber::toString': function does not take 0 arguments
>>   error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
>
> I expect toString() method to work without any arguments, so I dont know why I got such an error. Full build log up to error can be found below.

Ah, so you're building on Windows (I missed that earlier). Still, it should 
work. As for toString(), it takes a status parameter in ICU 64.

Andi..

**Comment by ertas** [comment]
I can definitely try using previous versions of ICU and pyICU, but I also want to identify the problem. It seems to me there is something wrong with the compiler that Distutils use:

Under "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN" there are multiple cl.exe. When I try to call cl.exe on one of them I get the following result successfully:
> Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x86

However when I run that for the compiler that Distutils use, it throws a System Error that reads mspdb140.dll was not found.

[PyICU_v2_3 build_err.txt](https://github.com/ovalhub/pyicu/files/3030653/PyICU_v2_3.build_err.txt)
In this log as you can see python uses cl in path"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe"

I come to think that the error may be originating from that. Also there seems to be nothing wrong with the measurementunit.cpp:
```
#if U_ICU_VERSION_HEX >= VERSION_HEX(60, 0, 0)
    UnicodeString u;

    STATUS_CALL(u = icu::number::NumberFormatter::withLocale(
        Locale::getDefault())
                .unit(self->object->getUnit())
                .unitWidth(UNumberUnitWidth::UNUM_UNIT_WIDTH_FULL_NAME)
                .formatDouble(self->object->getNumber().getDouble(), status)
#if U_ICU_VERSION_HEX >= VERSION_HEX(64, 0, 0)
                .toString(status));
#else
                .toString());
#endif

    return PyUnicode_FromUnicodeString(&u);
#else
```
Python version is 3.5.4 for further information, Os is Win 10 but as I said they are probably irrelevant.

I will dig into the issue if I have more time.

Thank you Andi for the helpfull feedbacks
Mustafa

**Comment by ovalhub** [comment]
On Mon, 1 Apr 2019, Mustafa wrote:

> I can definitely try using previous versions of ICU and pyICU, but I also want to identify the problem. It seems to me there is something wrong with the compiler that Distutils use:
>
> Under "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN" there are multiple cl.exe. When I try to call cl.exe on one of them I get the following result successfully:
>> Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x86
>
> However when I run that for the compiler that Distutils use, it throws a System Error that reads mspdb140.dll was not found.
>
> [PyICU_v2_3 build_err.txt](https://github.com/ovalhub/pyicu/files/3030653/PyICU_v2_3.build_err.txt)
> In this log as you can see python uses cl in path"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe"
>
> I come to think that the error may be originating from that. Also there seems to be nothing wrong with the measurementunit.cpp:
> ```
> #if U_ICU_VERSION_HEX >= VERSION_HEX(60, 0, 0)
>    UnicodeString u;
>
>    STATUS_CALL(u = icu::number::NumberFormatter::withLocale(
>        Locale::getDefault())
>                .unit(self->object->getUnit())
>                .unitWidth(UNumberUnitWidth::UNUM_UNIT_WIDTH_FULL_NAME)
>                .formatDouble(self->object->getNumber().getDouble(), status)
> #if U_ICU_VERSION_HEX >= VERSION_HEX(64, 0, 0)
>                .toString(status));
> #else
>                .toString());
> #endif
>
>    return PyUnicode_FromUnicodeString(&u);
> #else
> ```
> Python version is 3.5.4 for further information, Os is Win 10 but as I said they are probably irrelevant.
>
> I will dig into the issue if I have more time.

Yeah, your version of the code looks correct too.

Your compiler setup is messed up and you need to resolve that before you can 
proceed. Maybe it's time you eliminate one of the compilers you have 
installed, keeping the newer one ?
Or rebuild python with the newest compiler (assuming distutils then 
remembers you used this compiler) ?

Andi..

**Comment by cgohlke** [comment]
Msvc doesn't like this kind of macros/preprocessor constructs:
```
#if U_ICU_VERSION_HEX >= VERSION_HEX(60, 0, 0)
    UnicodeString u;

    STATUS_CALL(u = icu::number::NumberFormatter::withLocale(
        Locale::getDefault())
                .unit(self->object->getUnit())
                .unitWidth(UNumberUnitWidth::UNUM_UNIT_WIDTH_FULL_NAME)
                .formatDouble(self->object->getNumber().getDouble(), status)
#if U_ICU_VERSION_HEX >= VERSION_HEX(64, 0, 0)
                .toString(status));
#else
                .toString());
#endif

    return PyUnicode_FromUnicodeString(&u);
#else
```

I am using:
```
diff --git a/measureunit.cpp b/measureunit.cpp
index d50bde7..017a2b3 100644
--- a/measureunit.cpp
+++ b/measureunit.cpp
@@ -2010,14 +2010,19 @@ static PyObject *t_measure_str(t_measure *self)
 #if U_ICU_VERSION_HEX >= VERSION_HEX(60, 0, 0)
     UnicodeString u;

+#if U_ICU_VERSION_HEX >= VERSION_HEX(64, 0, 0)
     STATUS_CALL(u = icu::number::NumberFormatter::withLocale(
         Locale::getDefault())
                 .unit(self->object->getUnit())
                 .unitWidth(UNumberUnitWidth::UNUM_UNIT_WIDTH_FULL_NAME)
                 .formatDouble(self->object->getNumber().getDouble(), status)
-#if U_ICU_VERSION_HEX >= VERSION_HEX(64, 0, 0)
                 .toString(status));
 #else
+    STATUS_CALL(u = icu::number::NumberFormatter::withLocale(
+        Locale::getDefault())
+                .unit(self->object->getUnit())
+                .unitWidth(UNumberUnitWidth::UNUM_UNIT_WIDTH_FULL_NAME)
+                .formatDouble(self->object->getNumber().getDouble(), status)
                 .toString());
 #endif
```

>  However when I run that for the compiler that Distutils use, it throws a System Error that reads mspdb140.dll was not found.

That is probably because you are trying to run the compiler from an environment that has not been initialized, e.g. by running the vcvarsall batch file `"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64`

**Comment by ovalhub** [comment]
On Mon, 1 Apr 2019, Christoph Gohlke wrote:

> Msvc doesn't like this kind of macros/preprocessor constructs:

That is a shame. I'm assuming it's valid standard C++, though.
If it isn't, I'd like to get a complete patch from you (I don't have access 
to MSVC or Windows myself anymore) so that this is properly fixed in PyICU.

If it is valid standard C++, however, then MSVC needs to be fix its bug,
coding around it is undesirable.

Thanks !

Andi..

**Comment by ertas** [comment]
> On Mon, 1 Apr 2019, Christoph Gohlke wrote:
>  Msvc doesn't like this kind of macros/preprocessor constructs:
It seems that is the root cause of the problem. When I deleted the nested macro (I asuumed a constant ICU version), I didnt get any error in build.

However I came across a link error this time. In which path is icuin.lib supposed to be generated, the linker couldnt find it.
I am unsure if I should install by pip'ing the tar file. (i.e. "pip install PyICU-2.3.tar"). Any more recommendations Andi?

Thank you!
Mustafa

**Comment by ovalhub** [comment]
> On Apr 1, 2019, at 23:02, Mustafa <notifications@github.com> wrote:
> 
> On Mon, 1 Apr 2019, Christoph Gohlke wrote:
> Msvc doesn't like this kind of macros/preprocessor constructs:
> It seems that is the root cause of the problem. When I deleted the nested macro (I asuumed a constant ICU version), I didnt get any error in build.
> 
> However I came across a link error this time. In which path is icuin.lib supposed to be generated, the linker couldnt find it.
> I am unsure if I should install by pip'ing the tar file. (i.e. "pip install PyICU-2.3.tar"). Any more recommendations Andi?
> 
You're supposed to ensure that the settings in setup.py are correct for your platform. If icuin.lib is not correct in there, replace that with the correct lib, maybe something like icuin64.lib ? (I don't know, I can't build on Windows anymore, I don't have access to that software anymore).

Andi..

**Comment by ertas** [comment]
Thank you Andi for the help.
